return {
  ast = {
  ["loc"] = {
    ["start"] = {
      ["line"] = 1,
      ["offset"] = 0,
      ["col"] = 1,
    },
    ["source"] = "",
    ["end"] = {
      ["line"] = 39,
      ["offset"] = 0,
      ["col"] = 31,
    },
  },
  ["comments"] = {
  },
  ["type"] = "Chunk",
  ["body"] = {
    [1] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 1,
              ["offset"] = 6,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 1,
              ["offset"] = 6,
              ["col"] = 7,
            },
          },
          ["name"] = "binary_val",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 1,
          ["offset"] = 0,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 2,
          ["offset"] = 28,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["value"] = 42,
          ["lua_version"] = "5.3",
          ["raw"] = "0b101010",
          ["loc"] = {
            ["start"] = {
              ["line"] = 1,
              ["offset"] = 19,
              ["col"] = 20,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 1,
              ["offset"] = 19,
              ["col"] = 20,
            },
          },
          ["type"] = "NumericLiteral",
          ["is_lua53_feature"] = true,
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [2] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 2,
              ["offset"] = 34,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 2,
              ["offset"] = 34,
              ["col"] = 7,
            },
          },
          ["name"] = "hex_float",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 2,
          ["offset"] = 28,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 3,
          ["offset"] = 54,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["value"] = 12.0,
          ["lua_version"] = "5.3",
          ["raw"] = "0x1.8p3",
          ["loc"] = {
            ["start"] = {
              ["line"] = 2,
              ["offset"] = 46,
              ["col"] = 19,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 2,
              ["offset"] = 46,
              ["col"] = 19,
            },
          },
          ["type"] = "NumericLiteral",
          ["is_lua53_feature"] = true,
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [3] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 3,
              ["offset"] = 60,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 3,
              ["offset"] = 60,
              ["col"] = 7,
            },
          },
          ["name"] = "utf8_str",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 3,
          ["offset"] = 54,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 5,
          ["offset"] = 93,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["value"] = "Unicode: u{1F680}",
          ["lua_version"] = "5.3",
          ["raw"] = "\"Unicode: \\u{1F680}\"",
          ["loc"] = {
            ["start"] = {
              ["line"] = 3,
              ["offset"] = 71,
              ["col"] = 18,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 3,
              ["offset"] = 71,
              ["col"] = 18,
            },
          },
          ["type"] = "StringLiteral",
          ["is_lua53_feature"] = true,
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [4] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 5,
              ["offset"] = 99,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 5,
              ["offset"] = 99,
              ["col"] = 7,
            },
          },
          ["name"] = "a",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
        [2] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 5,
              ["offset"] = 102,
              ["col"] = 10,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 5,
              ["offset"] = 102,
              ["col"] = 10,
            },
          },
          ["name"] = "b",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 5,
          ["offset"] = 93,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 6,
          ["offset"] = 112,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["value"] = 42,
          ["raw"] = "42",
          ["loc"] = {
            ["start"] = {
              ["line"] = 5,
              ["offset"] = 106,
              ["col"] = 14,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 5,
              ["offset"] = 106,
              ["col"] = 14,
            },
          },
          ["type"] = "NumericLiteral",
          ["is_lua53_feature"] = false,
        },
        [2] = {
          ["value"] = 7,
          ["raw"] = "7",
          ["loc"] = {
            ["start"] = {
              ["line"] = 5,
              ["offset"] = 110,
              ["col"] = 18,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 5,
              ["offset"] = 110,
              ["col"] = 18,
            },
          },
          ["type"] = "NumericLiteral",
          ["is_lua53_feature"] = false,
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [5] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 6,
              ["offset"] = 118,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 6,
              ["offset"] = 118,
              ["col"] = 7,
            },
          },
          ["name"] = "bitwise_and",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 6,
          ["offset"] = 112,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 7,
          ["offset"] = 138,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 29,
              ["offset"] = 566,
              ["col"] = 34,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 30,
              ["offset"] = 586,
              ["col"] = 19,
            },
          },
          ["lua_version"] = "5.3",
          ["left"] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 6,
                ["offset"] = 132,
                ["col"] = 21,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 6,
                ["offset"] = 132,
                ["col"] = 21,
              },
            },
            ["name"] = "a",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
          ["right"] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 6,
                ["offset"] = 136,
                ["col"] = 25,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 6,
                ["offset"] = 136,
                ["col"] = 25,
              },
            },
            ["name"] = "b",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
          ["substituted_operator"] = "&",
          ["operator"] = "&",
          ["swap_operands"] = false,
          ["expression_depth"] = 1,
          ["is_lua53_feature"] = true,
          ["type"] = "BinaryExpression",
          ["metamethod"] = "__band",
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [6] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 7,
              ["offset"] = 144,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 7,
              ["offset"] = 144,
              ["col"] = 7,
            },
          },
          ["name"] = "bitwise_or",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 7,
          ["offset"] = 138,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 8,
          ["offset"] = 163,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 34,
              ["offset"] = 689,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 35,
              ["offset"] = 718,
              ["col"] = 1,
            },
          },
          ["lua_version"] = "5.3",
          ["left"] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 7,
                ["offset"] = 157,
                ["col"] = 20,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 7,
                ["offset"] = 157,
                ["col"] = 20,
              },
            },
            ["name"] = "a",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
          ["right"] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 7,
                ["offset"] = 161,
                ["col"] = 24,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 7,
                ["offset"] = 161,
                ["col"] = 24,
              },
            },
            ["name"] = "b",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
          ["substituted_operator"] = "|",
          ["operator"] = "|",
          ["swap_operands"] = false,
          ["expression_depth"] = 1,
          ["is_lua53_feature"] = true,
          ["type"] = "BinaryExpression",
          ["metamethod"] = "__bor",
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [7] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 8,
              ["offset"] = 169,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 8,
              ["offset"] = 169,
              ["col"] = 7,
            },
          },
          ["name"] = "bitwise_not",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 8,
          ["offset"] = 163,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 9,
          ["offset"] = 186,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["is_lua53_feature"] = true,
          ["lua_version"] = "5.3",
          ["expression_depth"] = 2,
          ["loc"] = {
            ["start"] = {
              ["line"] = 8,
              ["offset"] = 183,
              ["col"] = 21,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 8,
              ["offset"] = 184,
              ["col"] = 22,
            },
          },
          ["metamethod"] = "__bnot",
          ["operator"] = "~",
          ["type"] = "UnaryExpression",
          ["argument"] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 8,
                ["offset"] = 184,
                ["col"] = 22,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 8,
                ["offset"] = 184,
                ["col"] = 22,
              },
            },
            ["name"] = "a",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [8] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 9,
              ["offset"] = 192,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 9,
              ["offset"] = 192,
              ["col"] = 7,
            },
          },
          ["name"] = "left_shift",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 9,
          ["offset"] = 186,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 10,
          ["offset"] = 212,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 9,
              ["offset"] = 207,
              ["col"] = 22,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 9,
              ["offset"] = 207,
              ["col"] = 22,
            },
          },
          ["lua_version"] = "5.3",
          ["left"] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 9,
                ["offset"] = 205,
                ["col"] = 20,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 9,
                ["offset"] = 205,
                ["col"] = 20,
              },
            },
            ["name"] = "a",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
          ["right"] = {
            ["value"] = 2,
            ["raw"] = "2",
            ["loc"] = {
              ["start"] = {
                ["line"] = 9,
                ["offset"] = 210,
                ["col"] = 25,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 9,
                ["offset"] = 210,
                ["col"] = 25,
              },
            },
            ["type"] = "NumericLiteral",
            ["is_lua53_feature"] = false,
          },
          ["substituted_operator"] = "<<",
          ["operator"] = "<<",
          ["swap_operands"] = false,
          ["expression_depth"] = 1,
          ["is_lua53_feature"] = true,
          ["type"] = "BinaryExpression",
          ["metamethod"] = "__shl",
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [9] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 10,
              ["offset"] = 218,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 10,
              ["offset"] = 218,
              ["col"] = 7,
            },
          },
          ["name"] = "right_shift",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 10,
          ["offset"] = 212,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 11,
          ["offset"] = 239,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 10,
              ["offset"] = 234,
              ["col"] = 23,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 10,
              ["offset"] = 234,
              ["col"] = 23,
            },
          },
          ["lua_version"] = "5.3",
          ["left"] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 10,
                ["offset"] = 232,
                ["col"] = 21,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 10,
                ["offset"] = 232,
                ["col"] = 21,
              },
            },
            ["name"] = "a",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
          ["right"] = {
            ["value"] = 1,
            ["raw"] = "1",
            ["loc"] = {
              ["start"] = {
                ["line"] = 10,
                ["offset"] = 237,
                ["col"] = 26,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 10,
                ["offset"] = 237,
                ["col"] = 26,
              },
            },
            ["type"] = "NumericLiteral",
            ["is_lua53_feature"] = false,
          },
          ["substituted_operator"] = ">>",
          ["operator"] = ">>",
          ["swap_operands"] = false,
          ["expression_depth"] = 1,
          ["is_lua53_feature"] = true,
          ["type"] = "BinaryExpression",
          ["metamethod"] = "__shr",
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [10] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 11,
              ["offset"] = 245,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 11,
              ["offset"] = 245,
              ["col"] = 7,
            },
          },
          ["name"] = "int_division",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 11,
          ["offset"] = 239,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 13,
          ["offset"] = 268,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 11,
              ["offset"] = 262,
              ["col"] = 24,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 11,
              ["offset"] = 262,
              ["col"] = 24,
            },
          },
          ["lua_version"] = "5.3",
          ["left"] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 11,
                ["offset"] = 260,
                ["col"] = 22,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 11,
                ["offset"] = 260,
                ["col"] = 22,
              },
            },
            ["name"] = "a",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
          ["right"] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 11,
                ["offset"] = 265,
                ["col"] = 27,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 11,
                ["offset"] = 265,
                ["col"] = 27,
              },
            },
            ["name"] = "b",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
          ["substituted_operator"] = "//",
          ["operator"] = "//",
          ["swap_operands"] = false,
          ["expression_depth"] = 1,
          ["is_lua53_feature"] = true,
          ["type"] = "BinaryExpression",
          ["metamethod"] = "__idiv",
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [11] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 13,
              ["offset"] = 274,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 13,
              ["offset"] = 290,
              ["col"] = 23,
            },
          },
          ["name"] = "const_var",
          ["type"] = "Identifier",
          ["attributes"] = {
            ["const"] = true,
          },
        },
      },
      ["lua_version"] = "5.4",
      ["loc"] = {
        ["start"] = {
          ["line"] = 13,
          ["offset"] = 268,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 14,
          ["offset"] = 298,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = true,
      ["init"] = {
        [1] = {
          ["value"] = 100,
          ["raw"] = "100",
          ["loc"] = {
            ["start"] = {
              ["line"] = 13,
              ["offset"] = 294,
              ["col"] = 27,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 13,
              ["offset"] = 294,
              ["col"] = 27,
            },
          },
          ["type"] = "NumericLiteral",
          ["is_lua53_feature"] = false,
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = true,
    },
    [12] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 14,
              ["offset"] = 304,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 14,
              ["offset"] = 304,
              ["col"] = 7,
            },
          },
          ["name"] = "mt",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 14,
          ["offset"] = 298,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 15,
          ["offset"] = 312,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["has_metamethods"] = false,
          ["fields"] = {
          },
          ["type"] = "TableConstructorExpression",
          ["metamethods"] = {
          },
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [13] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 15,
          ["offset"] = 312,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 17,
          ["offset"] = 367,
          ["col"] = 1,
        },
      },
      ["identifier"] = {
        ["indexer"] = ".",
        ["identifier"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 15,
              ["offset"] = 324,
              ["col"] = 13,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 15,
              ["offset"] = 324,
              ["col"] = 13,
            },
          },
          ["name"] = "__close",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
        ["type"] = "MemberExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 15,
              ["offset"] = 321,
              ["col"] = 10,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 15,
              ["offset"] = 321,
              ["col"] = 10,
            },
          },
          ["name"] = "mt",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["isLocal"] = false,
      ["parameters"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 15,
              ["offset"] = 332,
              ["col"] = 21,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 15,
              ["offset"] = 332,
              ["col"] = 21,
            },
          },
          ["name"] = "self",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "FunctionDeclaration",
      ["body"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 16,
              ["offset"] = 342,
              ["col"] = 5,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 16,
              ["offset"] = 342,
              ["col"] = 5,
            },
          },
          ["expression"] = {
            ["expression_depth"] = 1,
            ["arguments"] = {
              [1] = {
                ["value"] = "Resource closed",
                ["raw"] = "\"Resource closed\"",
                ["loc"] = {
                  ["start"] = {
                    ["line"] = 16,
                    ["offset"] = 348,
                    ["col"] = 11,
                  },
                  ["source"] = "",
                  ["end"] = {
                    ["line"] = 16,
                    ["offset"] = 348,
                    ["col"] = 11,
                  },
                },
                ["type"] = "StringLiteral",
                ["is_lua53_feature"] = false,
              },
            },
            ["has_metamethod"] = true,
            ["potential_metamethod"] = "__call",
            ["is_method_call"] = false,
            ["type"] = "CallExpression",
            ["base"] = {
              ["loc"] = {
                ["start"] = {
                  ["line"] = 16,
                  ["offset"] = 342,
                  ["col"] = 5,
                },
                ["source"] = "",
                ["end"] = {
                  ["line"] = 16,
                  ["offset"] = 342,
                  ["col"] = 5,
                },
              },
              ["name"] = "print",
              ["type"] = "Identifier",
              ["attributes"] = {
              },
            },
          },
          ["type"] = "CallStatement",
        },
      },
    },
    [14] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 19,
          ["offset"] = 372,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 22,
          ["offset"] = 471,
          ["col"] = 1,
        },
      },
      ["body"] = {
        [1] = {
          ["variables"] = {
            [1] = {
              ["loc"] = {
                ["start"] = {
                  ["line"] = 20,
                  ["offset"] = 385,
                  ["col"] = 11,
                },
                ["source"] = "",
                ["end"] = {
                  ["line"] = 20,
                  ["offset"] = 395,
                  ["col"] = 21,
                },
              },
              ["name"] = "res",
              ["type"] = "Identifier",
              ["attributes"] = {
                ["close"] = true,
              },
            },
          },
          ["lua_version"] = "5.4",
          ["loc"] = {
            ["start"] = {
              ["line"] = 20,
              ["offset"] = 379,
              ["col"] = 5,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 21,
              ["offset"] = 424,
              ["col"] = 5,
            },
          },
          ["has_close_variables"] = true,
          ["has_const_variables"] = false,
          ["init"] = {
            [1] = {
              ["expression_depth"] = 2,
              ["arguments"] = {
                [1] = {
                  ["has_metamethods"] = false,
                  ["fields"] = {
                  },
                  ["type"] = "TableConstructorExpression",
                  ["metamethods"] = {
                  },
                },
                [2] = {
                  ["loc"] = {
                    ["start"] = {
                      ["line"] = 20,
                      ["offset"] = 416,
                      ["col"] = 42,
                    },
                    ["source"] = "",
                    ["end"] = {
                      ["line"] = 20,
                      ["offset"] = 416,
                      ["col"] = 42,
                    },
                  },
                  ["name"] = "mt",
                  ["type"] = "Identifier",
                  ["attributes"] = {
                  },
                },
              },
              ["has_metamethod"] = true,
              ["potential_metamethod"] = "__call",
              ["is_method_call"] = false,
              ["type"] = "CallExpression",
              ["base"] = {
                ["loc"] = {
                  ["start"] = {
                    ["line"] = 20,
                    ["offset"] = 399,
                    ["col"] = 25,
                  },
                  ["source"] = "",
                  ["end"] = {
                    ["line"] = 20,
                    ["offset"] = 399,
                    ["col"] = 25,
                  },
                },
                ["name"] = "setmetatable",
                ["type"] = "Identifier",
                ["attributes"] = {
                },
              },
            },
          },
          ["type"] = "LocalStatement",
          ["has_attributed_variables"] = true,
        },
        [2] = {
          ["variables"] = {
            [1] = {
              ["loc"] = {
                ["start"] = {
                  ["line"] = 21,
                  ["offset"] = 430,
                  ["col"] = 11,
                },
                ["source"] = "",
                ["end"] = {
                  ["line"] = 21,
                  ["offset"] = 446,
                  ["col"] = 27,
                },
              },
              ["name"] = "alt_res",
              ["type"] = "Identifier",
              ["attributes"] = {
                ["close"] = true,
              },
            },
          },
          ["lua_version"] = "5.4",
          ["loc"] = {
            ["start"] = {
              ["line"] = 21,
              ["offset"] = 424,
              ["col"] = 5,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 22,
              ["offset"] = 471,
              ["col"] = 1,
            },
          },
          ["has_close_variables"] = true,
          ["has_const_variables"] = false,
          ["init"] = {
            [1] = {
              ["expression_depth"] = 2,
              ["arguments"] = {
                [1] = {
                  ["has_metamethods"] = false,
                  ["fields"] = {
                  },
                  ["type"] = "TableConstructorExpression",
                  ["metamethods"] = {
                  },
                },
                [2] = {
                  ["loc"] = {
                    ["start"] = {
                      ["line"] = 21,
                      ["offset"] = 467,
                      ["col"] = 48,
                    },
                    ["source"] = "",
                    ["end"] = {
                      ["line"] = 21,
                      ["offset"] = 467,
                      ["col"] = 48,
                    },
                  },
                  ["name"] = "mt",
                  ["type"] = "Identifier",
                  ["attributes"] = {
                  },
                },
              },
              ["has_metamethod"] = true,
              ["potential_metamethod"] = "__call",
              ["is_method_call"] = false,
              ["type"] = "CallExpression",
              ["base"] = {
                ["loc"] = {
                  ["start"] = {
                    ["line"] = 21,
                    ["offset"] = 450,
                    ["col"] = 31,
                  },
                  ["source"] = "",
                  ["end"] = {
                    ["line"] = 21,
                    ["offset"] = 450,
                    ["col"] = 31,
                  },
                },
                ["name"] = "setmetatable",
                ["type"] = "Identifier",
                ["attributes"] = {
                },
              },
            },
          },
          ["type"] = "LocalStatement",
          ["has_attributed_variables"] = true,
        },
      },
      ["type"] = "DoStatement",
    },
    [15] = {
      ["variables"] = {
        [1] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 24,
              ["offset"] = 482,
              ["col"] = 7,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 24,
              ["offset"] = 482,
              ["col"] = 7,
            },
          },
          ["name"] = "sum",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["loc"] = {
        ["start"] = {
          ["line"] = 24,
          ["offset"] = 476,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 25,
          ["offset"] = 490,
          ["col"] = 1,
        },
      },
      ["has_close_variables"] = false,
      ["has_const_variables"] = false,
      ["init"] = {
        [1] = {
          ["value"] = 0,
          ["raw"] = "0",
          ["loc"] = {
            ["start"] = {
              ["line"] = 24,
              ["offset"] = 488,
              ["col"] = 13,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 24,
              ["offset"] = 488,
              ["col"] = 13,
            },
          },
          ["type"] = "NumericLiteral",
          ["is_lua53_feature"] = false,
        },
      },
      ["type"] = "LocalStatement",
      ["has_attributed_variables"] = false,
    },
    [16] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 25,
          ["offset"] = 490,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 27,
          ["offset"] = 528,
          ["col"] = 1,
        },
      },
      ["body"] = {
        [1] = {
          ["variables"] = {
            [1] = {
              ["loc"] = {
                ["start"] = {
                  ["line"] = 26,
                  ["offset"] = 514,
                  ["col"] = 5,
                },
                ["source"] = "",
                ["end"] = {
                  ["line"] = 26,
                  ["offset"] = 514,
                  ["col"] = 5,
                },
              },
              ["name"] = "sum",
              ["type"] = "Identifier",
              ["attributes"] = {
              },
            },
          },
          ["metamethod_ops"] = {
          },
          ["loc"] = {
            ["start"] = {
              ["line"] = 26,
              ["offset"] = 514,
              ["col"] = 5,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 27,
              ["offset"] = 528,
              ["col"] = 1,
            },
          },
          ["init"] = {
            [1] = {
              ["loc"] = {
                ["start"] = {
                  ["line"] = 26,
                  ["offset"] = 524,
                  ["col"] = 15,
                },
                ["source"] = "",
                ["end"] = {
                  ["line"] = 26,
                  ["offset"] = 524,
                  ["col"] = 15,
                },
              },
              ["left"] = {
                ["loc"] = {
                  ["start"] = {
                    ["line"] = 26,
                    ["offset"] = 520,
                    ["col"] = 11,
                  },
                  ["source"] = "",
                  ["end"] = {
                    ["line"] = 26,
                    ["offset"] = 520,
                    ["col"] = 11,
                  },
                },
                ["name"] = "sum",
                ["type"] = "Identifier",
                ["attributes"] = {
                },
              },
              ["right"] = {
                ["loc"] = {
                  ["start"] = {
                    ["line"] = 26,
                    ["offset"] = 526,
                    ["col"] = 17,
                  },
                  ["source"] = "",
                  ["end"] = {
                    ["line"] = 26,
                    ["offset"] = 526,
                    ["col"] = 17,
                  },
                },
                ["name"] = "i",
                ["type"] = "Identifier",
                ["attributes"] = {
                },
              },
              ["substituted_operator"] = "+",
              ["operator"] = "+",
              ["swap_operands"] = false,
              ["expression_depth"] = 1,
              ["is_lua53_feature"] = false,
              ["type"] = "BinaryExpression",
              ["metamethod"] = "__add",
            },
          },
          ["type"] = "AssignmentStatement",
          ["has_metamethods"] = false,
        },
      },
      ["step"] = {
        ["value"] = 2,
        ["raw"] = "2",
        ["loc"] = {
          ["start"] = {
            ["line"] = 25,
            ["offset"] = 505,
            ["col"] = 16,
          },
          ["source"] = "",
          ["end"] = {
            ["line"] = 25,
            ["offset"] = 505,
            ["col"] = 16,
          },
        },
        ["type"] = "NumericLiteral",
        ["is_lua53_feature"] = false,
      },
      ["stop"] = {
        ["value"] = 10,
        ["raw"] = "10",
        ["loc"] = {
          ["start"] = {
            ["line"] = 25,
            ["offset"] = 501,
            ["col"] = 12,
          },
          ["source"] = "",
          ["end"] = {
            ["line"] = 25,
            ["offset"] = 501,
            ["col"] = 12,
          },
        },
        ["type"] = "NumericLiteral",
        ["is_lua53_feature"] = false,
      },
      ["is_lua54_style"] = false,
      ["start"] = {
        ["value"] = 1,
        ["raw"] = "1",
        ["loc"] = {
          ["start"] = {
            ["line"] = 25,
            ["offset"] = 498,
            ["col"] = 9,
          },
          ["source"] = "",
          ["end"] = {
            ["line"] = 25,
            ["offset"] = 498,
            ["col"] = 9,
          },
        },
        ["type"] = "NumericLiteral",
        ["is_lua53_feature"] = false,
      },
      ["type"] = "ForNumericStatement",
      ["variable"] = {
        ["loc"] = {
          ["start"] = {
            ["line"] = 25,
            ["offset"] = 494,
            ["col"] = 5,
          },
          ["source"] = "",
          ["end"] = {
            ["line"] = 25,
            ["offset"] = 494,
            ["col"] = 5,
          },
        },
        ["name"] = "i",
        ["type"] = "Identifier",
        ["attributes"] = {
        },
      },
    },
    [17] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 29,
          ["offset"] = 533,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 29,
          ["offset"] = 533,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Binary value:",
            ["raw"] = "\"Binary value:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 29,
                ["offset"] = 539,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 29,
                ["offset"] = 539,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 29,
                ["offset"] = 556,
                ["col"] = 24,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 29,
                ["offset"] = 556,
                ["col"] = 24,
              },
            },
            ["name"] = "binary_val",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 29,
              ["offset"] = 533,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 29,
              ["offset"] = 533,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [18] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 30,
          ["offset"] = 568,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 30,
          ["offset"] = 568,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Hex float:",
            ["raw"] = "\"Hex float:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 30,
                ["offset"] = 574,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 30,
                ["offset"] = 574,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 30,
                ["offset"] = 588,
                ["col"] = 21,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 30,
                ["offset"] = 588,
                ["col"] = 21,
              },
            },
            ["name"] = "hex_float",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 30,
              ["offset"] = 568,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 30,
              ["offset"] = 568,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [19] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 31,
          ["offset"] = 599,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 31,
          ["offset"] = 599,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 31,
                ["offset"] = 605,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 31,
                ["offset"] = 605,
                ["col"] = 7,
              },
            },
            ["name"] = "utf8_str",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 31,
              ["offset"] = 599,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 31,
              ["offset"] = 599,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [20] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 32,
          ["offset"] = 615,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 32,
          ["offset"] = 615,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Bitwise AND:",
            ["raw"] = "\"Bitwise AND:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 32,
                ["offset"] = 621,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 32,
                ["offset"] = 621,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 32,
                ["offset"] = 637,
                ["col"] = 23,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 32,
                ["offset"] = 637,
                ["col"] = 23,
              },
            },
            ["name"] = "bitwise_and",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 32,
              ["offset"] = 615,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 32,
              ["offset"] = 615,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [21] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 33,
          ["offset"] = 650,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 33,
          ["offset"] = 650,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Bitwise OR:",
            ["raw"] = "\"Bitwise OR:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 33,
                ["offset"] = 656,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 33,
                ["offset"] = 656,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 33,
                ["offset"] = 671,
                ["col"] = 22,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 33,
                ["offset"] = 671,
                ["col"] = 22,
              },
            },
            ["name"] = "bitwise_or",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 33,
              ["offset"] = 650,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 33,
              ["offset"] = 650,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [22] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 34,
          ["offset"] = 683,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 34,
          ["offset"] = 683,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Bitwise NOT:",
            ["raw"] = "\"Bitwise NOT:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 34,
                ["offset"] = 689,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 34,
                ["offset"] = 689,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 34,
                ["offset"] = 705,
                ["col"] = 23,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 34,
                ["offset"] = 705,
                ["col"] = 23,
              },
            },
            ["name"] = "bitwise_not",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 34,
              ["offset"] = 683,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 34,
              ["offset"] = 683,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [23] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 35,
          ["offset"] = 718,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 35,
          ["offset"] = 718,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Left shift:",
            ["raw"] = "\"Left shift:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 35,
                ["offset"] = 724,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 35,
                ["offset"] = 724,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 35,
                ["offset"] = 739,
                ["col"] = 22,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 35,
                ["offset"] = 739,
                ["col"] = 22,
              },
            },
            ["name"] = "left_shift",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 35,
              ["offset"] = 718,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 35,
              ["offset"] = 718,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [24] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 36,
          ["offset"] = 751,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 36,
          ["offset"] = 751,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Right shift:",
            ["raw"] = "\"Right shift:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 36,
                ["offset"] = 757,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 36,
                ["offset"] = 757,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 36,
                ["offset"] = 773,
                ["col"] = 23,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 36,
                ["offset"] = 773,
                ["col"] = 23,
              },
            },
            ["name"] = "right_shift",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 36,
              ["offset"] = 751,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 36,
              ["offset"] = 751,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [25] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 37,
          ["offset"] = 786,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 37,
          ["offset"] = 786,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Integer division:",
            ["raw"] = "\"Integer division:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 37,
                ["offset"] = 792,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 37,
                ["offset"] = 792,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 37,
                ["offset"] = 813,
                ["col"] = 28,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 37,
                ["offset"] = 813,
                ["col"] = 28,
              },
            },
            ["name"] = "int_division",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 37,
              ["offset"] = 786,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 37,
              ["offset"] = 786,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [26] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 38,
          ["offset"] = 827,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 38,
          ["offset"] = 827,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Const variable:",
            ["raw"] = "\"Const variable:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 38,
                ["offset"] = 833,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 38,
                ["offset"] = 833,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 38,
                ["offset"] = 852,
                ["col"] = 26,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 38,
                ["offset"] = 852,
                ["col"] = 26,
              },
            },
            ["name"] = "const_var",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 38,
              ["offset"] = 827,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 38,
              ["offset"] = 827,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
    [27] = {
      ["loc"] = {
        ["start"] = {
          ["line"] = 39,
          ["offset"] = 863,
          ["col"] = 1,
        },
        ["source"] = "",
        ["end"] = {
          ["line"] = 39,
          ["offset"] = 863,
          ["col"] = 1,
        },
      },
      ["expression"] = {
        ["expression_depth"] = 1,
        ["arguments"] = {
          [1] = {
            ["value"] = "Sum of for loop:",
            ["raw"] = "\"Sum of for loop:\"",
            ["loc"] = {
              ["start"] = {
                ["line"] = 39,
                ["offset"] = 869,
                ["col"] = 7,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 39,
                ["offset"] = 869,
                ["col"] = 7,
              },
            },
            ["type"] = "StringLiteral",
            ["is_lua53_feature"] = false,
          },
          [2] = {
            ["loc"] = {
              ["start"] = {
                ["line"] = 39,
                ["offset"] = 889,
                ["col"] = 27,
              },
              ["source"] = "",
              ["end"] = {
                ["line"] = 39,
                ["offset"] = 889,
                ["col"] = 27,
              },
            },
            ["name"] = "sum",
            ["type"] = "Identifier",
            ["attributes"] = {
            },
          },
        },
        ["has_metamethod"] = true,
        ["potential_metamethod"] = "__call",
        ["is_method_call"] = false,
        ["type"] = "CallExpression",
        ["base"] = {
          ["loc"] = {
            ["start"] = {
              ["line"] = 39,
              ["offset"] = 863,
              ["col"] = 1,
            },
            ["source"] = "",
            ["end"] = {
              ["line"] = 39,
              ["offset"] = 863,
              ["col"] = 1,
            },
          },
          ["name"] = "print",
          ["type"] = "Identifier",
          ["attributes"] = {
          },
        },
      },
      ["type"] = "CallStatement",
    },
  },
},
  tokens = {
  [1] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 0,
    ["type"] = "KEYWORD",
    ["line"] = 1,
  },
  [2] = {
    ["value"] = "binary_val",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "binary_val",
    ["offset"] = 6,
    ["type"] = "IDENTIFIER",
    ["line"] = 1,
  },
  [3] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 18,
    ["raw"] = "=",
    ["offset"] = 17,
    ["type"] = "ASSIGN",
    ["line"] = 1,
  },
  [4] = {
    ["value"] = 42,
    ["source"] = "",
    ["col"] = 20,
    ["raw"] = "0b101010",
    ["offset"] = 19,
    ["type"] = "NUMBER",
    ["line"] = 1,
  },
  [5] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 28,
    ["type"] = "KEYWORD",
    ["line"] = 2,
  },
  [6] = {
    ["value"] = "hex_float",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "hex_float",
    ["offset"] = 34,
    ["type"] = "IDENTIFIER",
    ["line"] = 2,
  },
  [7] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 17,
    ["raw"] = "=",
    ["offset"] = 44,
    ["type"] = "ASSIGN",
    ["line"] = 2,
  },
  [8] = {
    ["value"] = 12.0,
    ["source"] = "",
    ["col"] = 19,
    ["raw"] = "0x1.8p3",
    ["offset"] = 46,
    ["type"] = "NUMBER",
    ["line"] = 2,
  },
  [9] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 54,
    ["type"] = "KEYWORD",
    ["line"] = 3,
  },
  [10] = {
    ["value"] = "utf8_str",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "utf8_str",
    ["offset"] = 60,
    ["type"] = "IDENTIFIER",
    ["line"] = 3,
  },
  [11] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 16,
    ["raw"] = "=",
    ["offset"] = 69,
    ["type"] = "ASSIGN",
    ["line"] = 3,
  },
  [12] = {
    ["value"] = "Unicode: u{1F680}",
    ["source"] = "",
    ["col"] = 18,
    ["raw"] = "\"Unicode: \\u{1F680}\"",
    ["offset"] = 71,
    ["type"] = "STRING",
    ["line"] = 3,
  },
  [13] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 93,
    ["type"] = "KEYWORD",
    ["line"] = 5,
  },
  [14] = {
    ["value"] = "a",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "a",
    ["offset"] = 99,
    ["type"] = "IDENTIFIER",
    ["line"] = 5,
  },
  [15] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 8,
    ["raw"] = ",",
    ["offset"] = 100,
    ["type"] = "COMMA",
    ["line"] = 5,
  },
  [16] = {
    ["value"] = "b",
    ["source"] = "",
    ["col"] = 10,
    ["raw"] = "b",
    ["offset"] = 102,
    ["type"] = "IDENTIFIER",
    ["line"] = 5,
  },
  [17] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 12,
    ["raw"] = "=",
    ["offset"] = 104,
    ["type"] = "ASSIGN",
    ["line"] = 5,
  },
  [18] = {
    ["value"] = 42,
    ["source"] = "",
    ["col"] = 14,
    ["raw"] = "42",
    ["offset"] = 106,
    ["type"] = "NUMBER",
    ["line"] = 5,
  },
  [19] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 16,
    ["raw"] = ",",
    ["offset"] = 108,
    ["type"] = "COMMA",
    ["line"] = 5,
  },
  [20] = {
    ["value"] = 7,
    ["source"] = "",
    ["col"] = 18,
    ["raw"] = "7",
    ["offset"] = 110,
    ["type"] = "NUMBER",
    ["line"] = 5,
  },
  [21] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 112,
    ["type"] = "KEYWORD",
    ["line"] = 6,
  },
  [22] = {
    ["value"] = "bitwise_and",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "bitwise_and",
    ["offset"] = 118,
    ["type"] = "IDENTIFIER",
    ["line"] = 6,
  },
  [23] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 19,
    ["raw"] = "=",
    ["offset"] = 130,
    ["type"] = "ASSIGN",
    ["line"] = 6,
  },
  [24] = {
    ["value"] = "a",
    ["source"] = "",
    ["col"] = 21,
    ["raw"] = "a",
    ["offset"] = 132,
    ["type"] = "IDENTIFIER",
    ["line"] = 6,
  },
  [25] = {
    ["value"] = "&",
    ["source"] = "",
    ["col"] = 23,
    ["raw"] = "&",
    ["offset"] = 134,
    ["type"] = "BAND",
    ["line"] = 6,
  },
  [26] = {
    ["value"] = "b",
    ["source"] = "",
    ["col"] = 25,
    ["raw"] = "b",
    ["offset"] = 136,
    ["type"] = "IDENTIFIER",
    ["line"] = 6,
  },
  [27] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 138,
    ["type"] = "KEYWORD",
    ["line"] = 7,
  },
  [28] = {
    ["value"] = "bitwise_or",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "bitwise_or",
    ["offset"] = 144,
    ["type"] = "IDENTIFIER",
    ["line"] = 7,
  },
  [29] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 18,
    ["raw"] = "=",
    ["offset"] = 155,
    ["type"] = "ASSIGN",
    ["line"] = 7,
  },
  [30] = {
    ["value"] = "a",
    ["source"] = "",
    ["col"] = 20,
    ["raw"] = "a",
    ["offset"] = 157,
    ["type"] = "IDENTIFIER",
    ["line"] = 7,
  },
  [31] = {
    ["value"] = "|",
    ["source"] = "",
    ["col"] = 22,
    ["raw"] = "|",
    ["offset"] = 159,
    ["type"] = "BOR",
    ["line"] = 7,
  },
  [32] = {
    ["value"] = "b",
    ["source"] = "",
    ["col"] = 24,
    ["raw"] = "b",
    ["offset"] = 161,
    ["type"] = "IDENTIFIER",
    ["line"] = 7,
  },
  [33] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 163,
    ["type"] = "KEYWORD",
    ["line"] = 8,
  },
  [34] = {
    ["value"] = "bitwise_not",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "bitwise_not",
    ["offset"] = 169,
    ["type"] = "IDENTIFIER",
    ["line"] = 8,
  },
  [35] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 19,
    ["raw"] = "=",
    ["offset"] = 181,
    ["type"] = "ASSIGN",
    ["line"] = 8,
  },
  [36] = {
    ["value"] = "~",
    ["source"] = "",
    ["col"] = 21,
    ["raw"] = "~",
    ["offset"] = 183,
    ["type"] = "BXOR",
    ["line"] = 8,
  },
  [37] = {
    ["value"] = "a",
    ["source"] = "",
    ["col"] = 22,
    ["raw"] = "a",
    ["offset"] = 184,
    ["type"] = "IDENTIFIER",
    ["line"] = 8,
  },
  [38] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 186,
    ["type"] = "KEYWORD",
    ["line"] = 9,
  },
  [39] = {
    ["value"] = "left_shift",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "left_shift",
    ["offset"] = 192,
    ["type"] = "IDENTIFIER",
    ["line"] = 9,
  },
  [40] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 18,
    ["raw"] = "=",
    ["offset"] = 203,
    ["type"] = "ASSIGN",
    ["line"] = 9,
  },
  [41] = {
    ["value"] = "a",
    ["source"] = "",
    ["col"] = 20,
    ["raw"] = "a",
    ["offset"] = 205,
    ["type"] = "IDENTIFIER",
    ["line"] = 9,
  },
  [42] = {
    ["value"] = "<<",
    ["source"] = "",
    ["col"] = 22,
    ["raw"] = "<<",
    ["offset"] = 207,
    ["type"] = "SHL",
    ["line"] = 9,
  },
  [43] = {
    ["value"] = 2,
    ["source"] = "",
    ["col"] = 25,
    ["raw"] = "2",
    ["offset"] = 210,
    ["type"] = "NUMBER",
    ["line"] = 9,
  },
  [44] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 212,
    ["type"] = "KEYWORD",
    ["line"] = 10,
  },
  [45] = {
    ["value"] = "right_shift",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "right_shift",
    ["offset"] = 218,
    ["type"] = "IDENTIFIER",
    ["line"] = 10,
  },
  [46] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 19,
    ["raw"] = "=",
    ["offset"] = 230,
    ["type"] = "ASSIGN",
    ["line"] = 10,
  },
  [47] = {
    ["value"] = "a",
    ["source"] = "",
    ["col"] = 21,
    ["raw"] = "a",
    ["offset"] = 232,
    ["type"] = "IDENTIFIER",
    ["line"] = 10,
  },
  [48] = {
    ["value"] = ">>",
    ["source"] = "",
    ["col"] = 23,
    ["raw"] = ">>",
    ["offset"] = 234,
    ["type"] = "SHR",
    ["line"] = 10,
  },
  [49] = {
    ["value"] = 1,
    ["source"] = "",
    ["col"] = 26,
    ["raw"] = "1",
    ["offset"] = 237,
    ["type"] = "NUMBER",
    ["line"] = 10,
  },
  [50] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 239,
    ["type"] = "KEYWORD",
    ["line"] = 11,
  },
  [51] = {
    ["value"] = "int_division",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "int_division",
    ["offset"] = 245,
    ["type"] = "IDENTIFIER",
    ["line"] = 11,
  },
  [52] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 20,
    ["raw"] = "=",
    ["offset"] = 258,
    ["type"] = "ASSIGN",
    ["line"] = 11,
  },
  [53] = {
    ["value"] = "a",
    ["source"] = "",
    ["col"] = 22,
    ["raw"] = "a",
    ["offset"] = 260,
    ["type"] = "IDENTIFIER",
    ["line"] = 11,
  },
  [54] = {
    ["value"] = "//",
    ["source"] = "",
    ["col"] = 24,
    ["raw"] = "//",
    ["offset"] = 262,
    ["type"] = "IDIV",
    ["line"] = 11,
  },
  [55] = {
    ["value"] = "b",
    ["source"] = "",
    ["col"] = 27,
    ["raw"] = "b",
    ["offset"] = 265,
    ["type"] = "IDENTIFIER",
    ["line"] = 11,
  },
  [56] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 268,
    ["type"] = "KEYWORD",
    ["line"] = 13,
  },
  [57] = {
    ["value"] = "const_var",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "const_var",
    ["offset"] = 274,
    ["type"] = "IDENTIFIER",
    ["line"] = 13,
  },
  [58] = {
    ["value"] = "<",
    ["source"] = "",
    ["col"] = 17,
    ["raw"] = "<",
    ["offset"] = 284,
    ["type"] = "LT_SYMBOL",
    ["line"] = 13,
  },
  [59] = {
    ["value"] = "const",
    ["source"] = "",
    ["col"] = 18,
    ["raw"] = "const",
    ["offset"] = 285,
    ["type"] = "ATTR_CONST",
    ["line"] = 13,
  },
  [60] = {
    ["value"] = ">",
    ["source"] = "",
    ["col"] = 23,
    ["raw"] = ">",
    ["offset"] = 290,
    ["type"] = "GT_SYMBOL",
    ["line"] = 13,
  },
  [61] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 25,
    ["raw"] = "=",
    ["offset"] = 292,
    ["type"] = "ASSIGN",
    ["line"] = 13,
  },
  [62] = {
    ["value"] = 100,
    ["source"] = "",
    ["col"] = 27,
    ["raw"] = "100",
    ["offset"] = 294,
    ["type"] = "NUMBER",
    ["line"] = 13,
  },
  [63] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 298,
    ["type"] = "KEYWORD",
    ["line"] = 14,
  },
  [64] = {
    ["value"] = "mt",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "mt",
    ["offset"] = 304,
    ["type"] = "IDENTIFIER",
    ["line"] = 14,
  },
  [65] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 10,
    ["raw"] = "=",
    ["offset"] = 307,
    ["type"] = "ASSIGN",
    ["line"] = 14,
  },
  [66] = {
    ["value"] = "{",
    ["source"] = "",
    ["col"] = 12,
    ["raw"] = "{",
    ["offset"] = 309,
    ["type"] = "LBRACE",
    ["line"] = 14,
  },
  [67] = {
    ["value"] = "}",
    ["source"] = "",
    ["col"] = 13,
    ["raw"] = "}",
    ["offset"] = 310,
    ["type"] = "RBRACE",
    ["line"] = 14,
  },
  [68] = {
    ["value"] = "function",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "function",
    ["offset"] = 312,
    ["type"] = "KEYWORD",
    ["line"] = 15,
  },
  [69] = {
    ["value"] = "mt",
    ["source"] = "",
    ["col"] = 10,
    ["raw"] = "mt",
    ["offset"] = 321,
    ["type"] = "IDENTIFIER",
    ["line"] = 15,
  },
  [70] = {
    ["value"] = ".",
    ["source"] = "",
    ["col"] = 12,
    ["raw"] = ".",
    ["offset"] = 323,
    ["type"] = "DOT",
    ["line"] = 15,
  },
  [71] = {
    ["value"] = "__close",
    ["source"] = "",
    ["col"] = 13,
    ["raw"] = "__close",
    ["offset"] = 324,
    ["type"] = "IDENTIFIER",
    ["line"] = 15,
  },
  [72] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 20,
    ["raw"] = "(",
    ["offset"] = 331,
    ["type"] = "LPAREN",
    ["line"] = 15,
  },
  [73] = {
    ["value"] = "self",
    ["source"] = "",
    ["col"] = 21,
    ["raw"] = "self",
    ["offset"] = 332,
    ["type"] = "IDENTIFIER",
    ["line"] = 15,
  },
  [74] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 25,
    ["raw"] = ")",
    ["offset"] = 336,
    ["type"] = "RPAREN",
    ["line"] = 15,
  },
  [75] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 5,
    ["raw"] = "print",
    ["offset"] = 342,
    ["type"] = "IDENTIFIER",
    ["line"] = 16,
  },
  [76] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 10,
    ["raw"] = "(",
    ["offset"] = 347,
    ["type"] = "LPAREN",
    ["line"] = 16,
  },
  [77] = {
    ["value"] = "Resource closed",
    ["source"] = "",
    ["col"] = 11,
    ["raw"] = "\"Resource closed\"",
    ["offset"] = 348,
    ["type"] = "STRING",
    ["line"] = 16,
  },
  [78] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 28,
    ["raw"] = ")",
    ["offset"] = 365,
    ["type"] = "RPAREN",
    ["line"] = 16,
  },
  [79] = {
    ["value"] = "end",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "end",
    ["offset"] = 367,
    ["type"] = "KEYWORD",
    ["line"] = 17,
  },
  [80] = {
    ["value"] = "do",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "do",
    ["offset"] = 372,
    ["type"] = "KEYWORD",
    ["line"] = 19,
  },
  [81] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 5,
    ["raw"] = "local",
    ["offset"] = 379,
    ["type"] = "KEYWORD",
    ["line"] = 20,
  },
  [82] = {
    ["value"] = "res",
    ["source"] = "",
    ["col"] = 11,
    ["raw"] = "res",
    ["offset"] = 385,
    ["type"] = "IDENTIFIER",
    ["line"] = 20,
  },
  [83] = {
    ["value"] = "<",
    ["source"] = "",
    ["col"] = 15,
    ["raw"] = "<",
    ["offset"] = 389,
    ["type"] = "LT_SYMBOL",
    ["line"] = 20,
  },
  [84] = {
    ["value"] = "close",
    ["source"] = "",
    ["col"] = 16,
    ["raw"] = "close",
    ["offset"] = 390,
    ["type"] = "ATTR_CLOSE",
    ["line"] = 20,
  },
  [85] = {
    ["value"] = ">",
    ["source"] = "",
    ["col"] = 21,
    ["raw"] = ">",
    ["offset"] = 395,
    ["type"] = "GT_SYMBOL",
    ["line"] = 20,
  },
  [86] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 23,
    ["raw"] = "=",
    ["offset"] = 397,
    ["type"] = "ASSIGN",
    ["line"] = 20,
  },
  [87] = {
    ["value"] = "setmetatable",
    ["source"] = "",
    ["col"] = 25,
    ["raw"] = "setmetatable",
    ["offset"] = 399,
    ["type"] = "IDENTIFIER",
    ["line"] = 20,
  },
  [88] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 37,
    ["raw"] = "(",
    ["offset"] = 411,
    ["type"] = "LPAREN",
    ["line"] = 20,
  },
  [89] = {
    ["value"] = "{",
    ["source"] = "",
    ["col"] = 38,
    ["raw"] = "{",
    ["offset"] = 412,
    ["type"] = "LBRACE",
    ["line"] = 20,
  },
  [90] = {
    ["value"] = "}",
    ["source"] = "",
    ["col"] = 39,
    ["raw"] = "}",
    ["offset"] = 413,
    ["type"] = "RBRACE",
    ["line"] = 20,
  },
  [91] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 40,
    ["raw"] = ",",
    ["offset"] = 414,
    ["type"] = "COMMA",
    ["line"] = 20,
  },
  [92] = {
    ["value"] = "mt",
    ["source"] = "",
    ["col"] = 42,
    ["raw"] = "mt",
    ["offset"] = 416,
    ["type"] = "IDENTIFIER",
    ["line"] = 20,
  },
  [93] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 44,
    ["raw"] = ")",
    ["offset"] = 418,
    ["type"] = "RPAREN",
    ["line"] = 20,
  },
  [94] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 5,
    ["raw"] = "local",
    ["offset"] = 424,
    ["type"] = "KEYWORD",
    ["line"] = 21,
  },
  [95] = {
    ["value"] = "alt_res",
    ["source"] = "",
    ["col"] = 11,
    ["raw"] = "alt_res",
    ["offset"] = 430,
    ["type"] = "IDENTIFIER",
    ["line"] = 21,
  },
  [96] = {
    ["value"] = "<",
    ["source"] = "",
    ["col"] = 19,
    ["raw"] = "<",
    ["offset"] = 438,
    ["type"] = "LT_SYMBOL",
    ["line"] = 21,
  },
  [97] = {
    ["value"] = "toclose",
    ["source"] = "",
    ["col"] = 20,
    ["raw"] = "toclose",
    ["offset"] = 439,
    ["type"] = "ATTR_TOCLOSE",
    ["line"] = 21,
  },
  [98] = {
    ["value"] = ">",
    ["source"] = "",
    ["col"] = 27,
    ["raw"] = ">",
    ["offset"] = 446,
    ["type"] = "GT_SYMBOL",
    ["line"] = 21,
  },
  [99] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 29,
    ["raw"] = "=",
    ["offset"] = 448,
    ["type"] = "ASSIGN",
    ["line"] = 21,
  },
  [100] = {
    ["value"] = "setmetatable",
    ["source"] = "",
    ["col"] = 31,
    ["raw"] = "setmetatable",
    ["offset"] = 450,
    ["type"] = "IDENTIFIER",
    ["line"] = 21,
  },
  [101] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 43,
    ["raw"] = "(",
    ["offset"] = 462,
    ["type"] = "LPAREN",
    ["line"] = 21,
  },
  [102] = {
    ["value"] = "{",
    ["source"] = "",
    ["col"] = 44,
    ["raw"] = "{",
    ["offset"] = 463,
    ["type"] = "LBRACE",
    ["line"] = 21,
  },
  [103] = {
    ["value"] = "}",
    ["source"] = "",
    ["col"] = 45,
    ["raw"] = "}",
    ["offset"] = 464,
    ["type"] = "RBRACE",
    ["line"] = 21,
  },
  [104] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 46,
    ["raw"] = ",",
    ["offset"] = 465,
    ["type"] = "COMMA",
    ["line"] = 21,
  },
  [105] = {
    ["value"] = "mt",
    ["source"] = "",
    ["col"] = 48,
    ["raw"] = "mt",
    ["offset"] = 467,
    ["type"] = "IDENTIFIER",
    ["line"] = 21,
  },
  [106] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 50,
    ["raw"] = ")",
    ["offset"] = 469,
    ["type"] = "RPAREN",
    ["line"] = 21,
  },
  [107] = {
    ["value"] = "end",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "end",
    ["offset"] = 471,
    ["type"] = "KEYWORD",
    ["line"] = 22,
  },
  [108] = {
    ["value"] = "local",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "local",
    ["offset"] = 476,
    ["type"] = "KEYWORD",
    ["line"] = 24,
  },
  [109] = {
    ["value"] = "sum",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "sum",
    ["offset"] = 482,
    ["type"] = "IDENTIFIER",
    ["line"] = 24,
  },
  [110] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 11,
    ["raw"] = "=",
    ["offset"] = 486,
    ["type"] = "ASSIGN",
    ["line"] = 24,
  },
  [111] = {
    ["value"] = 0,
    ["source"] = "",
    ["col"] = 13,
    ["raw"] = "0",
    ["offset"] = 488,
    ["type"] = "NUMBER",
    ["line"] = 24,
  },
  [112] = {
    ["value"] = "for",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "for",
    ["offset"] = 490,
    ["type"] = "KEYWORD",
    ["line"] = 25,
  },
  [113] = {
    ["value"] = "i",
    ["source"] = "",
    ["col"] = 5,
    ["raw"] = "i",
    ["offset"] = 494,
    ["type"] = "IDENTIFIER",
    ["line"] = 25,
  },
  [114] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "=",
    ["offset"] = 496,
    ["type"] = "ASSIGN",
    ["line"] = 25,
  },
  [115] = {
    ["value"] = 1,
    ["source"] = "",
    ["col"] = 9,
    ["raw"] = "1",
    ["offset"] = 498,
    ["type"] = "NUMBER",
    ["line"] = 25,
  },
  [116] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 10,
    ["raw"] = ",",
    ["offset"] = 499,
    ["type"] = "COMMA",
    ["line"] = 25,
  },
  [117] = {
    ["value"] = 10,
    ["source"] = "",
    ["col"] = 12,
    ["raw"] = "10",
    ["offset"] = 501,
    ["type"] = "NUMBER",
    ["line"] = 25,
  },
  [118] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 14,
    ["raw"] = ",",
    ["offset"] = 503,
    ["type"] = "COMMA",
    ["line"] = 25,
  },
  [119] = {
    ["value"] = 2,
    ["source"] = "",
    ["col"] = 16,
    ["raw"] = "2",
    ["offset"] = 505,
    ["type"] = "NUMBER",
    ["line"] = 25,
  },
  [120] = {
    ["value"] = "do",
    ["source"] = "",
    ["col"] = 18,
    ["raw"] = "do",
    ["offset"] = 507,
    ["type"] = "KEYWORD",
    ["line"] = 25,
  },
  [121] = {
    ["value"] = "sum",
    ["source"] = "",
    ["col"] = 5,
    ["raw"] = "sum",
    ["offset"] = 514,
    ["type"] = "IDENTIFIER",
    ["line"] = 26,
  },
  [122] = {
    ["value"] = "=",
    ["source"] = "",
    ["col"] = 9,
    ["raw"] = "=",
    ["offset"] = 518,
    ["type"] = "ASSIGN",
    ["line"] = 26,
  },
  [123] = {
    ["value"] = "sum",
    ["source"] = "",
    ["col"] = 11,
    ["raw"] = "sum",
    ["offset"] = 520,
    ["type"] = "IDENTIFIER",
    ["line"] = 26,
  },
  [124] = {
    ["value"] = "+",
    ["source"] = "",
    ["col"] = 15,
    ["raw"] = "+",
    ["offset"] = 524,
    ["type"] = "ADD",
    ["line"] = 26,
  },
  [125] = {
    ["value"] = "i",
    ["source"] = "",
    ["col"] = 17,
    ["raw"] = "i",
    ["offset"] = 526,
    ["type"] = "IDENTIFIER",
    ["line"] = 26,
  },
  [126] = {
    ["value"] = "end",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "end",
    ["offset"] = 528,
    ["type"] = "KEYWORD",
    ["line"] = 27,
  },
  [127] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 533,
    ["type"] = "IDENTIFIER",
    ["line"] = 29,
  },
  [128] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 538,
    ["type"] = "LPAREN",
    ["line"] = 29,
  },
  [129] = {
    ["value"] = "Binary value:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Binary value:\"",
    ["offset"] = 539,
    ["type"] = "STRING",
    ["line"] = 29,
  },
  [130] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 22,
    ["raw"] = ",",
    ["offset"] = 554,
    ["type"] = "COMMA",
    ["line"] = 29,
  },
  [131] = {
    ["value"] = "binary_val",
    ["source"] = "",
    ["col"] = 24,
    ["raw"] = "binary_val",
    ["offset"] = 556,
    ["type"] = "IDENTIFIER",
    ["line"] = 29,
  },
  [132] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 34,
    ["raw"] = ")",
    ["offset"] = 566,
    ["type"] = "RPAREN",
    ["line"] = 29,
  },
  [133] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 568,
    ["type"] = "IDENTIFIER",
    ["line"] = 30,
  },
  [134] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 573,
    ["type"] = "LPAREN",
    ["line"] = 30,
  },
  [135] = {
    ["value"] = "Hex float:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Hex float:\"",
    ["offset"] = 574,
    ["type"] = "STRING",
    ["line"] = 30,
  },
  [136] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 19,
    ["raw"] = ",",
    ["offset"] = 586,
    ["type"] = "COMMA",
    ["line"] = 30,
  },
  [137] = {
    ["value"] = "hex_float",
    ["source"] = "",
    ["col"] = 21,
    ["raw"] = "hex_float",
    ["offset"] = 588,
    ["type"] = "IDENTIFIER",
    ["line"] = 30,
  },
  [138] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 30,
    ["raw"] = ")",
    ["offset"] = 597,
    ["type"] = "RPAREN",
    ["line"] = 30,
  },
  [139] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 599,
    ["type"] = "IDENTIFIER",
    ["line"] = 31,
  },
  [140] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 604,
    ["type"] = "LPAREN",
    ["line"] = 31,
  },
  [141] = {
    ["value"] = "utf8_str",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "utf8_str",
    ["offset"] = 605,
    ["type"] = "IDENTIFIER",
    ["line"] = 31,
  },
  [142] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 15,
    ["raw"] = ")",
    ["offset"] = 613,
    ["type"] = "RPAREN",
    ["line"] = 31,
  },
  [143] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 615,
    ["type"] = "IDENTIFIER",
    ["line"] = 32,
  },
  [144] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 620,
    ["type"] = "LPAREN",
    ["line"] = 32,
  },
  [145] = {
    ["value"] = "Bitwise AND:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Bitwise AND:\"",
    ["offset"] = 621,
    ["type"] = "STRING",
    ["line"] = 32,
  },
  [146] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 21,
    ["raw"] = ",",
    ["offset"] = 635,
    ["type"] = "COMMA",
    ["line"] = 32,
  },
  [147] = {
    ["value"] = "bitwise_and",
    ["source"] = "",
    ["col"] = 23,
    ["raw"] = "bitwise_and",
    ["offset"] = 637,
    ["type"] = "IDENTIFIER",
    ["line"] = 32,
  },
  [148] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 34,
    ["raw"] = ")",
    ["offset"] = 648,
    ["type"] = "RPAREN",
    ["line"] = 32,
  },
  [149] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 650,
    ["type"] = "IDENTIFIER",
    ["line"] = 33,
  },
  [150] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 655,
    ["type"] = "LPAREN",
    ["line"] = 33,
  },
  [151] = {
    ["value"] = "Bitwise OR:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Bitwise OR:\"",
    ["offset"] = 656,
    ["type"] = "STRING",
    ["line"] = 33,
  },
  [152] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 20,
    ["raw"] = ",",
    ["offset"] = 669,
    ["type"] = "COMMA",
    ["line"] = 33,
  },
  [153] = {
    ["value"] = "bitwise_or",
    ["source"] = "",
    ["col"] = 22,
    ["raw"] = "bitwise_or",
    ["offset"] = 671,
    ["type"] = "IDENTIFIER",
    ["line"] = 33,
  },
  [154] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 32,
    ["raw"] = ")",
    ["offset"] = 681,
    ["type"] = "RPAREN",
    ["line"] = 33,
  },
  [155] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 683,
    ["type"] = "IDENTIFIER",
    ["line"] = 34,
  },
  [156] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 688,
    ["type"] = "LPAREN",
    ["line"] = 34,
  },
  [157] = {
    ["value"] = "Bitwise NOT:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Bitwise NOT:\"",
    ["offset"] = 689,
    ["type"] = "STRING",
    ["line"] = 34,
  },
  [158] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 21,
    ["raw"] = ",",
    ["offset"] = 703,
    ["type"] = "COMMA",
    ["line"] = 34,
  },
  [159] = {
    ["value"] = "bitwise_not",
    ["source"] = "",
    ["col"] = 23,
    ["raw"] = "bitwise_not",
    ["offset"] = 705,
    ["type"] = "IDENTIFIER",
    ["line"] = 34,
  },
  [160] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 34,
    ["raw"] = ")",
    ["offset"] = 716,
    ["type"] = "RPAREN",
    ["line"] = 34,
  },
  [161] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 718,
    ["type"] = "IDENTIFIER",
    ["line"] = 35,
  },
  [162] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 723,
    ["type"] = "LPAREN",
    ["line"] = 35,
  },
  [163] = {
    ["value"] = "Left shift:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Left shift:\"",
    ["offset"] = 724,
    ["type"] = "STRING",
    ["line"] = 35,
  },
  [164] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 20,
    ["raw"] = ",",
    ["offset"] = 737,
    ["type"] = "COMMA",
    ["line"] = 35,
  },
  [165] = {
    ["value"] = "left_shift",
    ["source"] = "",
    ["col"] = 22,
    ["raw"] = "left_shift",
    ["offset"] = 739,
    ["type"] = "IDENTIFIER",
    ["line"] = 35,
  },
  [166] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 32,
    ["raw"] = ")",
    ["offset"] = 749,
    ["type"] = "RPAREN",
    ["line"] = 35,
  },
  [167] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 751,
    ["type"] = "IDENTIFIER",
    ["line"] = 36,
  },
  [168] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 756,
    ["type"] = "LPAREN",
    ["line"] = 36,
  },
  [169] = {
    ["value"] = "Right shift:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Right shift:\"",
    ["offset"] = 757,
    ["type"] = "STRING",
    ["line"] = 36,
  },
  [170] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 21,
    ["raw"] = ",",
    ["offset"] = 771,
    ["type"] = "COMMA",
    ["line"] = 36,
  },
  [171] = {
    ["value"] = "right_shift",
    ["source"] = "",
    ["col"] = 23,
    ["raw"] = "right_shift",
    ["offset"] = 773,
    ["type"] = "IDENTIFIER",
    ["line"] = 36,
  },
  [172] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 34,
    ["raw"] = ")",
    ["offset"] = 784,
    ["type"] = "RPAREN",
    ["line"] = 36,
  },
  [173] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 786,
    ["type"] = "IDENTIFIER",
    ["line"] = 37,
  },
  [174] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 791,
    ["type"] = "LPAREN",
    ["line"] = 37,
  },
  [175] = {
    ["value"] = "Integer division:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Integer division:\"",
    ["offset"] = 792,
    ["type"] = "STRING",
    ["line"] = 37,
  },
  [176] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 26,
    ["raw"] = ",",
    ["offset"] = 811,
    ["type"] = "COMMA",
    ["line"] = 37,
  },
  [177] = {
    ["value"] = "int_division",
    ["source"] = "",
    ["col"] = 28,
    ["raw"] = "int_division",
    ["offset"] = 813,
    ["type"] = "IDENTIFIER",
    ["line"] = 37,
  },
  [178] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 40,
    ["raw"] = ")",
    ["offset"] = 825,
    ["type"] = "RPAREN",
    ["line"] = 37,
  },
  [179] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 827,
    ["type"] = "IDENTIFIER",
    ["line"] = 38,
  },
  [180] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 832,
    ["type"] = "LPAREN",
    ["line"] = 38,
  },
  [181] = {
    ["value"] = "Const variable:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Const variable:\"",
    ["offset"] = 833,
    ["type"] = "STRING",
    ["line"] = 38,
  },
  [182] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 24,
    ["raw"] = ",",
    ["offset"] = 850,
    ["type"] = "COMMA",
    ["line"] = 38,
  },
  [183] = {
    ["value"] = "const_var",
    ["source"] = "",
    ["col"] = 26,
    ["raw"] = "const_var",
    ["offset"] = 852,
    ["type"] = "IDENTIFIER",
    ["line"] = 38,
  },
  [184] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 35,
    ["raw"] = ")",
    ["offset"] = 861,
    ["type"] = "RPAREN",
    ["line"] = 38,
  },
  [185] = {
    ["value"] = "print",
    ["source"] = "",
    ["col"] = 1,
    ["raw"] = "print",
    ["offset"] = 863,
    ["type"] = "IDENTIFIER",
    ["line"] = 39,
  },
  [186] = {
    ["value"] = "(",
    ["source"] = "",
    ["col"] = 6,
    ["raw"] = "(",
    ["offset"] = 868,
    ["type"] = "LPAREN",
    ["line"] = 39,
  },
  [187] = {
    ["value"] = "Sum of for loop:",
    ["source"] = "",
    ["col"] = 7,
    ["raw"] = "\"Sum of for loop:\"",
    ["offset"] = 869,
    ["type"] = "STRING",
    ["line"] = 39,
  },
  [188] = {
    ["value"] = ",",
    ["source"] = "",
    ["col"] = 25,
    ["raw"] = ",",
    ["offset"] = 887,
    ["type"] = "COMMA",
    ["line"] = 39,
  },
  [189] = {
    ["value"] = "sum",
    ["source"] = "",
    ["col"] = 27,
    ["raw"] = "sum",
    ["offset"] = 889,
    ["type"] = "IDENTIFIER",
    ["line"] = 39,
  },
  [190] = {
    ["value"] = ")",
    ["source"] = "",
    ["col"] = 30,
    ["raw"] = ")",
    ["offset"] = 892,
    ["type"] = "RPAREN",
    ["line"] = 39,
  },
  [191] = {
    ["value"] = "",
    ["source"] = "",
    ["col"] = 31,
    ["raw"] = "",
    ["offset"] = 0,
    ["type"] = "EOF",
    ["line"] = 39,
  },
}
}