return {
  [1] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [2] = {
    ["col"] = 7,
    ["value"] = "expr1",
    ["line"] = 1,
    ["type"] = "IDENTIFIER",
    ["raw"] = "expr1",
  },
  [3] = {
    ["col"] = 13,
    ["value"] = "=",
    ["line"] = 1,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [4] = {
    ["col"] = 15,
    ["value"] = "(",
    ["line"] = 1,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [5] = {
    ["col"] = 16,
    ["value"] = "(",
    ["line"] = 1,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [6] = {
    ["col"] = 17,
    ["value"] = "(",
    ["line"] = 1,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [7] = {
    ["col"] = 18,
    ["value"] = 1,
    ["line"] = 1,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [8] = {
    ["col"] = 20,
    ["value"] = "+",
    ["line"] = 1,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [9] = {
    ["col"] = 22,
    ["value"] = 2,
    ["line"] = 1,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [10] = {
    ["col"] = 23,
    ["value"] = ")",
    ["line"] = 1,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [11] = {
    ["col"] = 25,
    ["value"] = "*",
    ["line"] = 1,
    ["type"] = "MUL",
    ["raw"] = "*",
  },
  [12] = {
    ["col"] = 27,
    ["value"] = 3,
    ["line"] = 1,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [13] = {
    ["col"] = 29,
    ["value"] = "-",
    ["line"] = 1,
    ["type"] = "SUB",
    ["raw"] = "-",
  },
  [14] = {
    ["col"] = 31,
    ["value"] = "(",
    ["line"] = 1,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [15] = {
    ["col"] = 32,
    ["value"] = 4,
    ["line"] = 1,
    ["type"] = "NUMBER",
    ["raw"] = "4",
  },
  [16] = {
    ["col"] = 34,
    ["value"] = "/",
    ["line"] = 1,
    ["type"] = "DIV",
    ["raw"] = "/",
  },
  [17] = {
    ["col"] = 36,
    ["value"] = 2,
    ["line"] = 1,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [18] = {
    ["col"] = 37,
    ["value"] = ")",
    ["line"] = 1,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [19] = {
    ["col"] = 38,
    ["value"] = ")",
    ["line"] = 1,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [20] = {
    ["col"] = 40,
    ["value"] = "^",
    ["line"] = 1,
    ["type"] = "POW",
    ["raw"] = "^",
  },
  [21] = {
    ["col"] = 42,
    ["value"] = 2,
    ["line"] = 1,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [22] = {
    ["col"] = 43,
    ["value"] = ")",
    ["line"] = 1,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [23] = {
    ["col"] = 45,
    ["value"] = "%",
    ["line"] = 1,
    ["type"] = "MOD",
    ["raw"] = "%",
  },
  [24] = {
    ["col"] = 47,
    ["value"] = 10,
    ["line"] = 1,
    ["type"] = "NUMBER",
    ["raw"] = "10",
  },
  [25] = {
    ["col"] = 50,
    ["value"] = "+",
    ["line"] = 1,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [26] = {
    ["col"] = 14,
    ["value"] = "(",
    ["line"] = 2,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [27] = {
    ["col"] = 15,
    ["value"] = 3,
    ["line"] = 2,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [28] = {
    ["col"] = 17,
    ["value"] = "&",
    ["line"] = 2,
    ["type"] = "BAND",
    ["raw"] = "&",
  },
  [29] = {
    ["col"] = 19,
    ["value"] = 7,
    ["line"] = 2,
    ["type"] = "NUMBER",
    ["raw"] = "7",
  },
  [30] = {
    ["col"] = 21,
    ["value"] = "|",
    ["line"] = 2,
    ["type"] = "BOR",
    ["raw"] = "|",
  },
  [31] = {
    ["col"] = 23,
    ["value"] = 2,
    ["line"] = 2,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [32] = {
    ["col"] = 24,
    ["value"] = ")",
    ["line"] = 2,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [33] = {
    ["col"] = 26,
    ["value"] = "*",
    ["line"] = 2,
    ["type"] = "MUL",
    ["raw"] = "*",
  },
  [34] = {
    ["col"] = 28,
    ["value"] = "(",
    ["line"] = 2,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [35] = {
    ["col"] = 29,
    ["value"] = "(",
    ["line"] = 2,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [36] = {
    ["col"] = 30,
    ["value"] = 1,
    ["line"] = 2,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [37] = {
    ["col"] = 32,
    ["value"] = "<<",
    ["line"] = 2,
    ["type"] = "SHL",
    ["raw"] = "<<",
  },
  [38] = {
    ["col"] = 35,
    ["value"] = 2,
    ["line"] = 2,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [39] = {
    ["col"] = 36,
    ["value"] = ")",
    ["line"] = 2,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [40] = {
    ["col"] = 38,
    ["value"] = ">>",
    ["line"] = 2,
    ["type"] = "SHR",
    ["raw"] = ">>",
  },
  [41] = {
    ["col"] = 41,
    ["value"] = 1,
    ["line"] = 2,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [42] = {
    ["col"] = 42,
    ["value"] = ")",
    ["line"] = 2,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [43] = {
    ["col"] = 44,
    ["value"] = "//",
    ["line"] = 2,
    ["type"] = "IDIV",
    ["raw"] = "//",
  },
  [44] = {
    ["col"] = 47,
    ["value"] = 3,
    ["line"] = 2,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [45] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 4,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [46] = {
    ["col"] = 7,
    ["value"] = "table1",
    ["line"] = 4,
    ["type"] = "IDENTIFIER",
    ["raw"] = "table1",
  },
  [47] = {
    ["col"] = 14,
    ["value"] = "=",
    ["line"] = 4,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [48] = {
    ["col"] = 16,
    ["value"] = "{",
    ["line"] = 4,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [49] = {
    ["col"] = 5,
    ["value"] = "[",
    ["line"] = 5,
    ["type"] = "LBRACKET",
    ["raw"] = "[",
  },
  [50] = {
    ["col"] = 6,
    ["value"] = 1,
    ["line"] = 5,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [51] = {
    ["col"] = 8,
    ["value"] = "+",
    ["line"] = 5,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [52] = {
    ["col"] = 10,
    ["value"] = 2,
    ["line"] = 5,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [53] = {
    ["col"] = 12,
    ["value"] = "*",
    ["line"] = 5,
    ["type"] = "MUL",
    ["raw"] = "*",
  },
  [54] = {
    ["col"] = 14,
    ["value"] = 3,
    ["line"] = 5,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [55] = {
    ["col"] = 15,
    ["value"] = "]",
    ["line"] = 5,
    ["type"] = "RBRACKET",
    ["raw"] = "]",
  },
  [56] = {
    ["col"] = 17,
    ["value"] = "=",
    ["line"] = 5,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [57] = {
    ["col"] = 19,
    ["value"] = 4,
    ["line"] = 5,
    ["type"] = "NUMBER",
    ["raw"] = "4",
  },
  [58] = {
    ["col"] = 21,
    ["value"] = "^",
    ["line"] = 5,
    ["type"] = "POW",
    ["raw"] = "^",
  },
  [59] = {
    ["col"] = 23,
    ["value"] = 2,
    ["line"] = 5,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [60] = {
    ["col"] = 25,
    ["value"] = "%",
    ["line"] = 5,
    ["type"] = "MOD",
    ["raw"] = "%",
  },
  [61] = {
    ["col"] = 27,
    ["value"] = 3,
    ["line"] = 5,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [62] = {
    ["col"] = 28,
    ["value"] = ",",
    ["line"] = 5,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [63] = {
    ["col"] = 5,
    ["value"] = "[",
    ["line"] = 6,
    ["type"] = "LBRACKET",
    ["raw"] = "[",
  },
  [64] = {
    ["col"] = 6,
    ["value"] = "key",
    ["line"] = 6,
    ["type"] = "STRING",
    ["raw"] = "\"key\"",
  },
  [65] = {
    ["col"] = 12,
    ["value"] = "..",
    ["line"] = 6,
    ["type"] = "CONCAT",
    ["raw"] = "..",
  },
  [66] = {
    ["col"] = 15,
    ["value"] = "(",
    ["line"] = 6,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [67] = {
    ["col"] = 16,
    ["value"] = 1,
    ["line"] = 6,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [68] = {
    ["col"] = 18,
    ["value"] = "+",
    ["line"] = 6,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [69] = {
    ["col"] = 20,
    ["value"] = 2,
    ["line"] = 6,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [70] = {
    ["col"] = 21,
    ["value"] = ")",
    ["line"] = 6,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [71] = {
    ["col"] = 22,
    ["value"] = "]",
    ["line"] = 6,
    ["type"] = "RBRACKET",
    ["raw"] = "]",
  },
  [72] = {
    ["col"] = 24,
    ["value"] = "=",
    ["line"] = 6,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [73] = {
    ["col"] = 26,
    ["value"] = "{",
    ["line"] = 6,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [74] = {
    ["col"] = 9,
    ["value"] = "nested",
    ["line"] = 7,
    ["type"] = "IDENTIFIER",
    ["raw"] = "nested",
  },
  [75] = {
    ["col"] = 16,
    ["value"] = "=",
    ["line"] = 7,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [76] = {
    ["col"] = 18,
    ["value"] = "{",
    ["line"] = 7,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [77] = {
    ["col"] = 13,
    ["value"] = "[",
    ["line"] = 8,
    ["type"] = "LBRACKET",
    ["raw"] = "[",
  },
  [78] = {
    ["col"] = 14,
    ["value"] = true,
    ["line"] = 8,
    ["type"] = "TRUE",
    ["raw"] = "true",
  },
  [79] = {
    ["col"] = 18,
    ["value"] = "]",
    ["line"] = 8,
    ["type"] = "RBRACKET",
    ["raw"] = "]",
  },
  [80] = {
    ["col"] = 20,
    ["value"] = "=",
    ["line"] = 8,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [81] = {
    ["col"] = 22,
    ["value"] = "function",
    ["line"] = 8,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [82] = {
    ["col"] = 30,
    ["value"] = "(",
    ["line"] = 8,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [83] = {
    ["col"] = 31,
    ["value"] = "x",
    ["line"] = 8,
    ["type"] = "IDENTIFIER",
    ["raw"] = "x",
  },
  [84] = {
    ["col"] = 32,
    ["value"] = ")",
    ["line"] = 8,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [85] = {
    ["col"] = 34,
    ["value"] = "return",
    ["line"] = 8,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [86] = {
    ["col"] = 41,
    ["value"] = "x",
    ["line"] = 8,
    ["type"] = "IDENTIFIER",
    ["raw"] = "x",
  },
  [87] = {
    ["col"] = 43,
    ["value"] = "*",
    ["line"] = 8,
    ["type"] = "MUL",
    ["raw"] = "*",
  },
  [88] = {
    ["col"] = 45,
    ["value"] = 2,
    ["line"] = 8,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [89] = {
    ["col"] = 47,
    ["value"] = "end",
    ["line"] = 8,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [90] = {
    ["col"] = 9,
    ["value"] = "}",
    ["line"] = 9,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [91] = {
    ["col"] = 10,
    ["value"] = ",",
    ["line"] = 9,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [92] = {
    ["col"] = 9,
    ["value"] = "value",
    ["line"] = 10,
    ["type"] = "IDENTIFIER",
    ["raw"] = "value",
  },
  [93] = {
    ["col"] = 15,
    ["value"] = "=",
    ["line"] = 10,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [94] = {
    ["col"] = 17,
    ["value"] = 10,
    ["line"] = 10,
    ["type"] = "NUMBER",
    ["raw"] = "10",
  },
  [95] = {
    ["col"] = 20,
    ["value"] = "<<",
    ["line"] = 10,
    ["type"] = "SHL",
    ["raw"] = "<<",
  },
  [96] = {
    ["col"] = 23,
    ["value"] = 2,
    ["line"] = 10,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [97] = {
    ["col"] = 5,
    ["value"] = "}",
    ["line"] = 11,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [98] = {
    ["col"] = 6,
    ["value"] = ",",
    ["line"] = 11,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [99] = {
    ["col"] = 5,
    ["value"] = "method",
    ["line"] = 12,
    ["type"] = "IDENTIFIER",
    ["raw"] = "method",
  },
  [100] = {
    ["col"] = 12,
    ["value"] = "=",
    ["line"] = 12,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [101] = {
    ["col"] = 14,
    ["value"] = "function",
    ["line"] = 12,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [102] = {
    ["col"] = 22,
    ["value"] = "(",
    ["line"] = 12,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [103] = {
    ["col"] = 23,
    ["value"] = "self",
    ["line"] = 12,
    ["type"] = "IDENTIFIER",
    ["raw"] = "self",
  },
  [104] = {
    ["col"] = 27,
    ["value"] = ",",
    ["line"] = 12,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [105] = {
    ["col"] = 29,
    ["value"] = "x",
    ["line"] = 12,
    ["type"] = "IDENTIFIER",
    ["raw"] = "x",
  },
  [106] = {
    ["col"] = 30,
    ["value"] = ")",
    ["line"] = 12,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [107] = {
    ["col"] = 9,
    ["value"] = "return",
    ["line"] = 13,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [108] = {
    ["col"] = 16,
    ["value"] = "function",
    ["line"] = 13,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [109] = {
    ["col"] = 24,
    ["value"] = "(",
    ["line"] = 13,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [110] = {
    ["col"] = 25,
    ["value"] = "y",
    ["line"] = 13,
    ["type"] = "IDENTIFIER",
    ["raw"] = "y",
  },
  [111] = {
    ["col"] = 26,
    ["value"] = ")",
    ["line"] = 13,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [112] = {
    ["col"] = 13,
    ["value"] = "return",
    ["line"] = 14,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [113] = {
    ["col"] = 20,
    ["value"] = "function",
    ["line"] = 14,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [114] = {
    ["col"] = 28,
    ["value"] = "(",
    ["line"] = 14,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [115] = {
    ["col"] = 29,
    ["value"] = "z",
    ["line"] = 14,
    ["type"] = "IDENTIFIER",
    ["raw"] = "z",
  },
  [116] = {
    ["col"] = 30,
    ["value"] = ")",
    ["line"] = 14,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [117] = {
    ["col"] = 17,
    ["value"] = "return",
    ["line"] = 15,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [118] = {
    ["col"] = 24,
    ["value"] = "x",
    ["line"] = 15,
    ["type"] = "IDENTIFIER",
    ["raw"] = "x",
  },
  [119] = {
    ["col"] = 26,
    ["value"] = "+",
    ["line"] = 15,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [120] = {
    ["col"] = 28,
    ["value"] = "y",
    ["line"] = 15,
    ["type"] = "IDENTIFIER",
    ["raw"] = "y",
  },
  [121] = {
    ["col"] = 30,
    ["value"] = "+",
    ["line"] = 15,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [122] = {
    ["col"] = 32,
    ["value"] = "z",
    ["line"] = 15,
    ["type"] = "IDENTIFIER",
    ["raw"] = "z",
  },
  [123] = {
    ["col"] = 13,
    ["value"] = "end",
    ["line"] = 16,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [124] = {
    ["col"] = 9,
    ["value"] = "end",
    ["line"] = 17,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [125] = {
    ["col"] = 5,
    ["value"] = "end",
    ["line"] = 18,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [126] = {
    ["col"] = 1,
    ["value"] = "}",
    ["line"] = 19,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [127] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 21,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [128] = {
    ["col"] = 7,
    ["value"] = "obj",
    ["line"] = 21,
    ["type"] = "IDENTIFIER",
    ["raw"] = "obj",
  },
  [129] = {
    ["col"] = 11,
    ["value"] = "=",
    ["line"] = 21,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [130] = {
    ["col"] = 13,
    ["value"] = "{",
    ["line"] = 21,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [131] = {
    ["col"] = 5,
    ["value"] = "chain",
    ["line"] = 22,
    ["type"] = "IDENTIFIER",
    ["raw"] = "chain",
  },
  [132] = {
    ["col"] = 11,
    ["value"] = "=",
    ["line"] = 22,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [133] = {
    ["col"] = 13,
    ["value"] = "function",
    ["line"] = 22,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [134] = {
    ["col"] = 21,
    ["value"] = "(",
    ["line"] = 22,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [135] = {
    ["col"] = 22,
    ["value"] = "self",
    ["line"] = 22,
    ["type"] = "IDENTIFIER",
    ["raw"] = "self",
  },
  [136] = {
    ["col"] = 26,
    ["value"] = ")",
    ["line"] = 22,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [137] = {
    ["col"] = 9,
    ["value"] = "return",
    ["line"] = 23,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [138] = {
    ["col"] = 16,
    ["value"] = "{",
    ["line"] = 23,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [139] = {
    ["col"] = 13,
    ["value"] = "method1",
    ["line"] = 24,
    ["type"] = "IDENTIFIER",
    ["raw"] = "method1",
  },
  [140] = {
    ["col"] = 21,
    ["value"] = "=",
    ["line"] = 24,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [141] = {
    ["col"] = 23,
    ["value"] = "function",
    ["line"] = 24,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [142] = {
    ["col"] = 31,
    ["value"] = "(",
    ["line"] = 24,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [143] = {
    ["col"] = 32,
    ["value"] = "self",
    ["line"] = 24,
    ["type"] = "IDENTIFIER",
    ["raw"] = "self",
  },
  [144] = {
    ["col"] = 36,
    ["value"] = ")",
    ["line"] = 24,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [145] = {
    ["col"] = 17,
    ["value"] = "return",
    ["line"] = 25,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [146] = {
    ["col"] = 24,
    ["value"] = "{",
    ["line"] = 25,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [147] = {
    ["col"] = 21,
    ["value"] = "method2",
    ["line"] = 26,
    ["type"] = "IDENTIFIER",
    ["raw"] = "method2",
  },
  [148] = {
    ["col"] = 29,
    ["value"] = "=",
    ["line"] = 26,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [149] = {
    ["col"] = 31,
    ["value"] = "function",
    ["line"] = 26,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [150] = {
    ["col"] = 39,
    ["value"] = "(",
    ["line"] = 26,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [151] = {
    ["col"] = 40,
    ["value"] = "self",
    ["line"] = 26,
    ["type"] = "IDENTIFIER",
    ["raw"] = "self",
  },
  [152] = {
    ["col"] = 44,
    ["value"] = ",",
    ["line"] = 26,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [153] = {
    ["col"] = 46,
    ["value"] = "x",
    ["line"] = 26,
    ["type"] = "IDENTIFIER",
    ["raw"] = "x",
  },
  [154] = {
    ["col"] = 47,
    ["value"] = ")",
    ["line"] = 26,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [155] = {
    ["col"] = 25,
    ["value"] = "return",
    ["line"] = 27,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [156] = {
    ["col"] = 32,
    ["value"] = "{",
    ["line"] = 27,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [157] = {
    ["col"] = 29,
    ["value"] = "method3",
    ["line"] = 28,
    ["type"] = "IDENTIFIER",
    ["raw"] = "method3",
  },
  [158] = {
    ["col"] = 37,
    ["value"] = "=",
    ["line"] = 28,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [159] = {
    ["col"] = 39,
    ["value"] = "function",
    ["line"] = 28,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [160] = {
    ["col"] = 47,
    ["value"] = "(",
    ["line"] = 28,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [161] = {
    ["col"] = 48,
    ["value"] = "self",
    ["line"] = 28,
    ["type"] = "IDENTIFIER",
    ["raw"] = "self",
  },
  [162] = {
    ["col"] = 52,
    ["value"] = ",",
    ["line"] = 28,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [163] = {
    ["col"] = 54,
    ["value"] = "y",
    ["line"] = 28,
    ["type"] = "IDENTIFIER",
    ["raw"] = "y",
  },
  [164] = {
    ["col"] = 55,
    ["value"] = ")",
    ["line"] = 28,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [165] = {
    ["col"] = 33,
    ["value"] = "return",
    ["line"] = 29,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [166] = {
    ["col"] = 40,
    ["value"] = "x",
    ["line"] = 29,
    ["type"] = "IDENTIFIER",
    ["raw"] = "x",
  },
  [167] = {
    ["col"] = 42,
    ["value"] = "+",
    ["line"] = 29,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [168] = {
    ["col"] = 44,
    ["value"] = "y",
    ["line"] = 29,
    ["type"] = "IDENTIFIER",
    ["raw"] = "y",
  },
  [169] = {
    ["col"] = 29,
    ["value"] = "end",
    ["line"] = 30,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [170] = {
    ["col"] = 25,
    ["value"] = "}",
    ["line"] = 31,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [171] = {
    ["col"] = 21,
    ["value"] = "end",
    ["line"] = 32,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [172] = {
    ["col"] = 17,
    ["value"] = "}",
    ["line"] = 33,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [173] = {
    ["col"] = 13,
    ["value"] = "end",
    ["line"] = 34,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [174] = {
    ["col"] = 9,
    ["value"] = "}",
    ["line"] = 35,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [175] = {
    ["col"] = 5,
    ["value"] = "end",
    ["line"] = 36,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [176] = {
    ["col"] = 1,
    ["value"] = "}",
    ["line"] = 37,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [177] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 39,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [178] = {
    ["col"] = 7,
    ["value"] = "result1",
    ["line"] = 39,
    ["type"] = "IDENTIFIER",
    ["raw"] = "result1",
  },
  [179] = {
    ["col"] = 15,
    ["value"] = "=",
    ["line"] = 39,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [180] = {
    ["col"] = 17,
    ["value"] = "string",
    ["line"] = 39,
    ["type"] = "IDENTIFIER",
    ["raw"] = "string",
  },
  [181] = {
    ["col"] = 23,
    ["value"] = ".",
    ["line"] = 39,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [182] = {
    ["col"] = 24,
    ["value"] = "gsub",
    ["line"] = 39,
    ["type"] = "IDENTIFIER",
    ["raw"] = "gsub",
  },
  [183] = {
    ["col"] = 28,
    ["value"] = "(",
    ["line"] = 39,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [184] = {
    ["col"] = 5,
    ["value"] = "table",
    ["line"] = 40,
    ["type"] = "IDENTIFIER",
    ["raw"] = "table",
  },
  [185] = {
    ["col"] = 10,
    ["value"] = ".",
    ["line"] = 40,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [186] = {
    ["col"] = 11,
    ["value"] = "concat",
    ["line"] = 40,
    ["type"] = "IDENTIFIER",
    ["raw"] = "concat",
  },
  [187] = {
    ["col"] = 17,
    ["value"] = "(",
    ["line"] = 40,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [188] = {
    ["col"] = 9,
    ["value"] = "{",
    ["line"] = 41,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [189] = {
    ["col"] = 13,
    ["value"] = "string",
    ["line"] = 42,
    ["type"] = "IDENTIFIER",
    ["raw"] = "string",
  },
  [190] = {
    ["col"] = 19,
    ["value"] = ".",
    ["line"] = 42,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [191] = {
    ["col"] = 20,
    ["value"] = "rep",
    ["line"] = 42,
    ["type"] = "IDENTIFIER",
    ["raw"] = "rep",
  },
  [192] = {
    ["col"] = 23,
    ["value"] = "(",
    ["line"] = 42,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [193] = {
    ["col"] = 24,
    ["value"] = "a",
    ["line"] = 42,
    ["type"] = "STRING",
    ["raw"] = "\"a\"",
  },
  [194] = {
    ["col"] = 27,
    ["value"] = ",",
    ["line"] = 42,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [195] = {
    ["col"] = 29,
    ["value"] = 2,
    ["line"] = 42,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [196] = {
    ["col"] = 31,
    ["value"] = "+",
    ["line"] = 42,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [197] = {
    ["col"] = 33,
    ["value"] = 3,
    ["line"] = 42,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [198] = {
    ["col"] = 34,
    ["value"] = ")",
    ["line"] = 42,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [199] = {
    ["col"] = 35,
    ["value"] = ",",
    ["line"] = 42,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [200] = {
    ["col"] = 13,
    ["value"] = "string",
    ["line"] = 43,
    ["type"] = "IDENTIFIER",
    ["raw"] = "string",
  },
  [201] = {
    ["col"] = 19,
    ["value"] = ".",
    ["line"] = 43,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [202] = {
    ["col"] = 20,
    ["value"] = "sub",
    ["line"] = 43,
    ["type"] = "IDENTIFIER",
    ["raw"] = "sub",
  },
  [203] = {
    ["col"] = 23,
    ["value"] = "(",
    ["line"] = 43,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [204] = {
    ["col"] = 24,
    ["value"] = "hello",
    ["line"] = 43,
    ["type"] = "STRING",
    ["raw"] = "\"hello\"",
  },
  [205] = {
    ["col"] = 31,
    ["value"] = ",",
    ["line"] = 43,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [206] = {
    ["col"] = 33,
    ["value"] = 2,
    ["line"] = 43,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [207] = {
    ["col"] = 34,
    ["value"] = ",",
    ["line"] = 43,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [208] = {
    ["col"] = 36,
    ["value"] = "-",
    ["line"] = 43,
    ["type"] = "SUB",
    ["raw"] = "-",
  },
  [209] = {
    ["col"] = 37,
    ["value"] = 2,
    ["line"] = 43,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [210] = {
    ["col"] = 38,
    ["value"] = ")",
    ["line"] = 43,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [211] = {
    ["col"] = 39,
    ["value"] = ",",
    ["line"] = 43,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [212] = {
    ["col"] = 13,
    ["value"] = 5,
    ["line"] = 44,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [213] = {
    ["col"] = 15,
    ["value"] = ">",
    ["line"] = 44,
    ["type"] = "GT",
    ["raw"] = ">",
  },
  [214] = {
    ["col"] = 17,
    ["value"] = 3,
    ["line"] = 44,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [215] = {
    ["col"] = 19,
    ["value"] = "and",
    ["line"] = 44,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [216] = {
    ["col"] = 23,
    ["value"] = "true",
    ["line"] = 44,
    ["type"] = "STRING",
    ["raw"] = "\"true\"",
  },
  [217] = {
    ["col"] = 30,
    ["value"] = "or",
    ["line"] = 44,
    ["type"] = "KEYWORD",
    ["raw"] = "or",
  },
  [218] = {
    ["col"] = 33,
    ["value"] = "false",
    ["line"] = 44,
    ["type"] = "STRING",
    ["raw"] = "\"false\"",
  },
  [219] = {
    ["col"] = 9,
    ["value"] = "}",
    ["line"] = 45,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [220] = {
    ["col"] = 10,
    ["value"] = ",",
    ["line"] = 45,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [221] = {
    ["col"] = 9,
    ["value"] = "-",
    ["line"] = 46,
    ["type"] = "STRING",
    ["raw"] = "\"-\"",
  },
  [222] = {
    ["col"] = 5,
    ["value"] = ")",
    ["line"] = 47,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [223] = {
    ["col"] = 6,
    ["value"] = ",",
    ["line"] = 47,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [224] = {
    ["col"] = 5,
    ["value"] = "(%w+)",
    ["line"] = 48,
    ["type"] = "STRING",
    ["raw"] = "\"(%w+)\"",
  },
  [225] = {
    ["col"] = 12,
    ["value"] = ",",
    ["line"] = 48,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [226] = {
    ["col"] = 5,
    ["value"] = "function",
    ["line"] = 49,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [227] = {
    ["col"] = 13,
    ["value"] = "(",
    ["line"] = 49,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [228] = {
    ["col"] = 14,
    ["value"] = "word",
    ["line"] = 49,
    ["type"] = "IDENTIFIER",
    ["raw"] = "word",
  },
  [229] = {
    ["col"] = 18,
    ["value"] = ")",
    ["line"] = 49,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [230] = {
    ["col"] = 9,
    ["value"] = "return",
    ["line"] = 50,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [231] = {
    ["col"] = 16,
    ["value"] = "string",
    ["line"] = 50,
    ["type"] = "IDENTIFIER",
    ["raw"] = "string",
  },
  [232] = {
    ["col"] = 22,
    ["value"] = ".",
    ["line"] = 50,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [233] = {
    ["col"] = 23,
    ["value"] = "upper",
    ["line"] = 50,
    ["type"] = "IDENTIFIER",
    ["raw"] = "upper",
  },
  [234] = {
    ["col"] = 28,
    ["value"] = "(",
    ["line"] = 50,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [235] = {
    ["col"] = 29,
    ["value"] = "word",
    ["line"] = 50,
    ["type"] = "IDENTIFIER",
    ["raw"] = "word",
  },
  [236] = {
    ["col"] = 33,
    ["value"] = ":",
    ["line"] = 50,
    ["type"] = "COLON",
    ["raw"] = ":",
  },
  [237] = {
    ["col"] = 34,
    ["value"] = "sub",
    ["line"] = 50,
    ["type"] = "IDENTIFIER",
    ["raw"] = "sub",
  },
  [238] = {
    ["col"] = 37,
    ["value"] = "(",
    ["line"] = 50,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [239] = {
    ["col"] = 38,
    ["value"] = 1,
    ["line"] = 50,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [240] = {
    ["col"] = 39,
    ["value"] = ",",
    ["line"] = 50,
    ["type"] = "COMMA",
    ["raw"] = ",",
  },
  [241] = {
    ["col"] = 41,
    ["value"] = 1,
    ["line"] = 50,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [242] = {
    ["col"] = 42,
    ["value"] = ")",
    ["line"] = 50,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [243] = {
    ["col"] = 43,
    ["value"] = ")",
    ["line"] = 50,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [244] = {
    ["col"] = 45,
    ["value"] = "..",
    ["line"] = 50,
    ["type"] = "CONCAT",
    ["raw"] = "..",
  },
  [245] = {
    ["col"] = 16,
    ["value"] = "string",
    ["line"] = 51,
    ["type"] = "IDENTIFIER",
    ["raw"] = "string",
  },
  [246] = {
    ["col"] = 22,
    ["value"] = ".",
    ["line"] = 51,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [247] = {
    ["col"] = 23,
    ["value"] = "lower",
    ["line"] = 51,
    ["type"] = "IDENTIFIER",
    ["raw"] = "lower",
  },
  [248] = {
    ["col"] = 28,
    ["value"] = "(",
    ["line"] = 51,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [249] = {
    ["col"] = 29,
    ["value"] = "word",
    ["line"] = 51,
    ["type"] = "IDENTIFIER",
    ["raw"] = "word",
  },
  [250] = {
    ["col"] = 33,
    ["value"] = ":",
    ["line"] = 51,
    ["type"] = "COLON",
    ["raw"] = ":",
  },
  [251] = {
    ["col"] = 34,
    ["value"] = "sub",
    ["line"] = 51,
    ["type"] = "IDENTIFIER",
    ["raw"] = "sub",
  },
  [252] = {
    ["col"] = 37,
    ["value"] = "(",
    ["line"] = 51,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [253] = {
    ["col"] = 38,
    ["value"] = 2,
    ["line"] = 51,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [254] = {
    ["col"] = 39,
    ["value"] = ")",
    ["line"] = 51,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [255] = {
    ["col"] = 40,
    ["value"] = ")",
    ["line"] = 51,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [256] = {
    ["col"] = 5,
    ["value"] = "end",
    ["line"] = 52,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [257] = {
    ["col"] = 1,
    ["value"] = ")",
    ["line"] = 53,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [258] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 55,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [259] = {
    ["col"] = 7,
    ["value"] = "result2",
    ["line"] = 55,
    ["type"] = "IDENTIFIER",
    ["raw"] = "result2",
  },
  [260] = {
    ["col"] = 15,
    ["value"] = "=",
    ["line"] = 55,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [261] = {
    ["col"] = 17,
    ["value"] = "(",
    ["line"] = 55,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [262] = {
    ["col"] = 18,
    ["value"] = 10,
    ["line"] = 55,
    ["type"] = "NUMBER",
    ["raw"] = "10",
  },
  [263] = {
    ["col"] = 21,
    ["value"] = ">",
    ["line"] = 55,
    ["type"] = "GT",
    ["raw"] = ">",
  },
  [264] = {
    ["col"] = 23,
    ["value"] = 5,
    ["line"] = 55,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [265] = {
    ["col"] = 25,
    ["value"] = "and",
    ["line"] = 55,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [266] = {
    ["col"] = 29,
    ["value"] = "{",
    ["line"] = 55,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [267] = {
    ["col"] = 5,
    ["value"] = "value",
    ["line"] = 56,
    ["type"] = "IDENTIFIER",
    ["raw"] = "value",
  },
  [268] = {
    ["col"] = 11,
    ["value"] = "=",
    ["line"] = 56,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [269] = {
    ["col"] = 13,
    ["value"] = 5,
    ["line"] = 56,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [270] = {
    ["col"] = 15,
    ["value"] = "<",
    ["line"] = 56,
    ["type"] = "LT",
    ["raw"] = "<",
  },
  [271] = {
    ["col"] = 17,
    ["value"] = 8,
    ["line"] = 56,
    ["type"] = "NUMBER",
    ["raw"] = "8",
  },
  [272] = {
    ["col"] = 19,
    ["value"] = "and",
    ["line"] = 56,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [273] = {
    ["col"] = 23,
    ["value"] = "(",
    ["line"] = 56,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [274] = {
    ["col"] = 9,
    ["value"] = "function",
    ["line"] = 57,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [275] = {
    ["col"] = 17,
    ["value"] = "(",
    ["line"] = 57,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [276] = {
    ["col"] = 18,
    ["value"] = ")",
    ["line"] = 57,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [277] = {
    ["col"] = 13,
    ["value"] = "if",
    ["line"] = 58,
    ["type"] = "KEYWORD",
    ["raw"] = "if",
  },
  [278] = {
    ["col"] = 16,
    ["value"] = 3,
    ["line"] = 58,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [279] = {
    ["col"] = 18,
    ["value"] = "<",
    ["line"] = 58,
    ["type"] = "LT",
    ["raw"] = "<",
  },
  [280] = {
    ["col"] = 20,
    ["value"] = 4,
    ["line"] = 58,
    ["type"] = "NUMBER",
    ["raw"] = "4",
  },
  [281] = {
    ["col"] = 22,
    ["value"] = "then",
    ["line"] = 58,
    ["type"] = "KEYWORD",
    ["raw"] = "then",
  },
  [282] = {
    ["col"] = 17,
    ["value"] = "return",
    ["line"] = 59,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [283] = {
    ["col"] = 24,
    ["value"] = "nested1",
    ["line"] = 59,
    ["type"] = "STRING",
    ["raw"] = "\"nested1\"",
  },
  [284] = {
    ["col"] = 13,
    ["value"] = "else",
    ["line"] = 60,
    ["type"] = "KEYWORD",
    ["raw"] = "else",
  },
  [285] = {
    ["col"] = 17,
    ["value"] = "return",
    ["line"] = 61,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [286] = {
    ["col"] = 24,
    ["value"] = "nested2",
    ["line"] = 61,
    ["type"] = "STRING",
    ["raw"] = "\"nested2\"",
  },
  [287] = {
    ["col"] = 13,
    ["value"] = "end",
    ["line"] = 62,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [288] = {
    ["col"] = 9,
    ["value"] = "end",
    ["line"] = 63,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [289] = {
    ["col"] = 5,
    ["value"] = ")",
    ["line"] = 64,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [290] = {
    ["col"] = 6,
    ["value"] = "(",
    ["line"] = 64,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [291] = {
    ["col"] = 7,
    ["value"] = ")",
    ["line"] = 64,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [292] = {
    ["col"] = 9,
    ["value"] = "or",
    ["line"] = 64,
    ["type"] = "KEYWORD",
    ["raw"] = "or",
  },
  [293] = {
    ["col"] = 12,
    ["value"] = "default",
    ["line"] = 64,
    ["type"] = "STRING",
    ["raw"] = "\"default\"",
  },
  [294] = {
    ["col"] = 1,
    ["value"] = "}",
    ["line"] = 65,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [295] = {
    ["col"] = 3,
    ["value"] = "or",
    ["line"] = 65,
    ["type"] = "KEYWORD",
    ["raw"] = "or",
  },
  [296] = {
    ["col"] = 6,
    ["value"] = "{",
    ["line"] = 65,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [297] = {
    ["col"] = 5,
    ["value"] = "fallback",
    ["line"] = 66,
    ["type"] = "IDENTIFIER",
    ["raw"] = "fallback",
  },
  [298] = {
    ["col"] = 14,
    ["value"] = "=",
    ["line"] = 66,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [299] = {
    ["col"] = 16,
    ["value"] = true,
    ["line"] = 66,
    ["type"] = "TRUE",
    ["raw"] = "true",
  },
  [300] = {
    ["col"] = 1,
    ["value"] = "}",
    ["line"] = 67,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [301] = {
    ["col"] = 2,
    ["value"] = ")",
    ["line"] = 67,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [302] = {
    ["col"] = 3,
    ["value"] = ".",
    ["line"] = 67,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [303] = {
    ["col"] = 4,
    ["value"] = "value",
    ["line"] = 67,
    ["type"] = "IDENTIFIER",
    ["raw"] = "value",
  },
  [304] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 69,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [305] = {
    ["col"] = 7,
    ["value"] = "deep_table",
    ["line"] = 69,
    ["type"] = "IDENTIFIER",
    ["raw"] = "deep_table",
  },
  [306] = {
    ["col"] = 18,
    ["value"] = "=",
    ["line"] = 69,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [307] = {
    ["col"] = 20,
    ["value"] = "{",
    ["line"] = 69,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [308] = {
    ["col"] = 21,
    ["value"] = "a",
    ["line"] = 69,
    ["type"] = "IDENTIFIER",
    ["raw"] = "a",
  },
  [309] = {
    ["col"] = 23,
    ["value"] = "=",
    ["line"] = 69,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [310] = {
    ["col"] = 25,
    ["value"] = "{",
    ["line"] = 69,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [311] = {
    ["col"] = 26,
    ["value"] = "b",
    ["line"] = 69,
    ["type"] = "IDENTIFIER",
    ["raw"] = "b",
  },
  [312] = {
    ["col"] = 28,
    ["value"] = "=",
    ["line"] = 69,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [313] = {
    ["col"] = 30,
    ["value"] = "{",
    ["line"] = 69,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [314] = {
    ["col"] = 31,
    ["value"] = "c",
    ["line"] = 69,
    ["type"] = "IDENTIFIER",
    ["raw"] = "c",
  },
  [315] = {
    ["col"] = 33,
    ["value"] = "=",
    ["line"] = 69,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [316] = {
    ["col"] = 35,
    ["value"] = "{",
    ["line"] = 69,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [317] = {
    ["col"] = 36,
    ["value"] = "d",
    ["line"] = 69,
    ["type"] = "IDENTIFIER",
    ["raw"] = "d",
  },
  [318] = {
    ["col"] = 38,
    ["value"] = "=",
    ["line"] = 69,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [319] = {
    ["col"] = 40,
    ["value"] = "{",
    ["line"] = 69,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [320] = {
    ["col"] = 41,
    ["value"] = "e",
    ["line"] = 69,
    ["type"] = "IDENTIFIER",
    ["raw"] = "e",
  },
  [321] = {
    ["col"] = 43,
    ["value"] = "=",
    ["line"] = 69,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [322] = {
    ["col"] = 45,
    ["value"] = "{",
    ["line"] = 69,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [323] = {
    ["col"] = 46,
    ["value"] = "f",
    ["line"] = 69,
    ["type"] = "IDENTIFIER",
    ["raw"] = "f",
  },
  [324] = {
    ["col"] = 48,
    ["value"] = "=",
    ["line"] = 69,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [325] = {
    ["col"] = 50,
    ["value"] = "{",
    ["line"] = 69,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [326] = {
    ["col"] = 51,
    ["value"] = "g",
    ["line"] = 69,
    ["type"] = "IDENTIFIER",
    ["raw"] = "g",
  },
  [327] = {
    ["col"] = 53,
    ["value"] = "=",
    ["line"] = 69,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [328] = {
    ["col"] = 55,
    ["value"] = 10,
    ["line"] = 69,
    ["type"] = "NUMBER",
    ["raw"] = "10",
  },
  [329] = {
    ["col"] = 57,
    ["value"] = "}",
    ["line"] = 69,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [330] = {
    ["col"] = 58,
    ["value"] = "}",
    ["line"] = 69,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [331] = {
    ["col"] = 59,
    ["value"] = "}",
    ["line"] = 69,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [332] = {
    ["col"] = 60,
    ["value"] = "}",
    ["line"] = 69,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [333] = {
    ["col"] = 61,
    ["value"] = "}",
    ["line"] = 69,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [334] = {
    ["col"] = 62,
    ["value"] = "}",
    ["line"] = 69,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [335] = {
    ["col"] = 63,
    ["value"] = "}",
    ["line"] = 69,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [336] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 70,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [337] = {
    ["col"] = 7,
    ["value"] = "deep_value",
    ["line"] = 70,
    ["type"] = "IDENTIFIER",
    ["raw"] = "deep_value",
  },
  [338] = {
    ["col"] = 18,
    ["value"] = "=",
    ["line"] = 70,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [339] = {
    ["col"] = 20,
    ["value"] = "deep_table",
    ["line"] = 70,
    ["type"] = "IDENTIFIER",
    ["raw"] = "deep_table",
  },
  [340] = {
    ["col"] = 30,
    ["value"] = ".",
    ["line"] = 70,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [341] = {
    ["col"] = 31,
    ["value"] = "a",
    ["line"] = 70,
    ["type"] = "IDENTIFIER",
    ["raw"] = "a",
  },
  [342] = {
    ["col"] = 32,
    ["value"] = ".",
    ["line"] = 70,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [343] = {
    ["col"] = 33,
    ["value"] = "b",
    ["line"] = 70,
    ["type"] = "IDENTIFIER",
    ["raw"] = "b",
  },
  [344] = {
    ["col"] = 34,
    ["value"] = ".",
    ["line"] = 70,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [345] = {
    ["col"] = 35,
    ["value"] = "c",
    ["line"] = 70,
    ["type"] = "IDENTIFIER",
    ["raw"] = "c",
  },
  [346] = {
    ["col"] = 36,
    ["value"] = ".",
    ["line"] = 70,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [347] = {
    ["col"] = 37,
    ["value"] = "d",
    ["line"] = 70,
    ["type"] = "IDENTIFIER",
    ["raw"] = "d",
  },
  [348] = {
    ["col"] = 38,
    ["value"] = ".",
    ["line"] = 70,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [349] = {
    ["col"] = 39,
    ["value"] = "e",
    ["line"] = 70,
    ["type"] = "IDENTIFIER",
    ["raw"] = "e",
  },
  [350] = {
    ["col"] = 40,
    ["value"] = ".",
    ["line"] = 70,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [351] = {
    ["col"] = 41,
    ["value"] = "f",
    ["line"] = 70,
    ["type"] = "IDENTIFIER",
    ["raw"] = "f",
  },
  [352] = {
    ["col"] = 42,
    ["value"] = ".",
    ["line"] = 70,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [353] = {
    ["col"] = 43,
    ["value"] = "g",
    ["line"] = 70,
    ["type"] = "IDENTIFIER",
    ["raw"] = "g",
  },
  [354] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 72,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [355] = {
    ["col"] = 7,
    ["value"] = "mixed_ops",
    ["line"] = 72,
    ["type"] = "IDENTIFIER",
    ["raw"] = "mixed_ops",
  },
  [356] = {
    ["col"] = 17,
    ["value"] = "=",
    ["line"] = 72,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [357] = {
    ["col"] = 19,
    ["value"] = "-",
    ["line"] = 72,
    ["type"] = "SUB",
    ["raw"] = "-",
  },
  [358] = {
    ["col"] = 20,
    ["value"] = "(",
    ["line"] = 72,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [359] = {
    ["col"] = 21,
    ["value"] = "(",
    ["line"] = 72,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [360] = {
    ["col"] = 22,
    ["value"] = "not",
    ["line"] = 72,
    ["type"] = "KEYWORD",
    ["raw"] = "not",
  },
  [361] = {
    ["col"] = 26,
    ["value"] = "(",
    ["line"] = 72,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [362] = {
    ["col"] = 27,
    ["value"] = 5,
    ["line"] = 72,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [363] = {
    ["col"] = 29,
    ["value"] = ">",
    ["line"] = 72,
    ["type"] = "GT",
    ["raw"] = ">",
  },
  [364] = {
    ["col"] = 31,
    ["value"] = 3,
    ["line"] = 72,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [365] = {
    ["col"] = 32,
    ["value"] = ")",
    ["line"] = 72,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [366] = {
    ["col"] = 33,
    ["value"] = ")",
    ["line"] = 72,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [367] = {
    ["col"] = 35,
    ["value"] = "and",
    ["line"] = 72,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [368] = {
    ["col"] = 39,
    ["value"] = "-",
    ["line"] = 72,
    ["type"] = "SUB",
    ["raw"] = "-",
  },
  [369] = {
    ["col"] = 40,
    ["value"] = "(",
    ["line"] = 72,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [370] = {
    ["col"] = 41,
    ["value"] = "-",
    ["line"] = 72,
    ["type"] = "SUB",
    ["raw"] = "-",
  },
  [371] = {
    ["col"] = 42,
    ["value"] = 5,
    ["line"] = 72,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [372] = {
    ["col"] = 43,
    ["value"] = ")",
    ["line"] = 72,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [373] = {
    ["col"] = 44,
    ["value"] = ")",
    ["line"] = 72,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [374] = {
    ["col"] = 46,
    ["value"] = "*",
    ["line"] = 72,
    ["type"] = "MUL",
    ["raw"] = "*",
  },
  [375] = {
    ["col"] = 48,
    ["value"] = "(",
    ["line"] = 72,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [376] = {
    ["col"] = 49,
    ["value"] = 3,
    ["line"] = 72,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [377] = {
    ["col"] = 51,
    ["value"] = "&",
    ["line"] = 72,
    ["type"] = "BAND",
    ["raw"] = "&",
  },
  [378] = {
    ["col"] = 53,
    ["value"] = 7,
    ["line"] = 72,
    ["type"] = "NUMBER",
    ["raw"] = "7",
  },
  [379] = {
    ["col"] = 54,
    ["value"] = ")",
    ["line"] = 72,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [380] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 74,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [381] = {
    ["col"] = 7,
    ["value"] = "counter",
    ["line"] = 74,
    ["type"] = "IDENTIFIER",
    ["raw"] = "counter",
  },
  [382] = {
    ["col"] = 15,
    ["value"] = "=",
    ["line"] = 74,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [383] = {
    ["col"] = 17,
    ["value"] = "(",
    ["line"] = 74,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [384] = {
    ["col"] = 18,
    ["value"] = "function",
    ["line"] = 74,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [385] = {
    ["col"] = 26,
    ["value"] = "(",
    ["line"] = 74,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [386] = {
    ["col"] = 27,
    ["value"] = "start",
    ["line"] = 74,
    ["type"] = "IDENTIFIER",
    ["raw"] = "start",
  },
  [387] = {
    ["col"] = 32,
    ["value"] = ")",
    ["line"] = 74,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [388] = {
    ["col"] = 5,
    ["value"] = "local",
    ["line"] = 75,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [389] = {
    ["col"] = 11,
    ["value"] = "count",
    ["line"] = 75,
    ["type"] = "IDENTIFIER",
    ["raw"] = "count",
  },
  [390] = {
    ["col"] = 17,
    ["value"] = "=",
    ["line"] = 75,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [391] = {
    ["col"] = 19,
    ["value"] = "start",
    ["line"] = 75,
    ["type"] = "IDENTIFIER",
    ["raw"] = "start",
  },
  [392] = {
    ["col"] = 5,
    ["value"] = "return",
    ["line"] = 76,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [393] = {
    ["col"] = 12,
    ["value"] = "function",
    ["line"] = 76,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [394] = {
    ["col"] = 20,
    ["value"] = "(",
    ["line"] = 76,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [395] = {
    ["col"] = 21,
    ["value"] = ")",
    ["line"] = 76,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [396] = {
    ["col"] = 9,
    ["value"] = "count",
    ["line"] = 77,
    ["type"] = "IDENTIFIER",
    ["raw"] = "count",
  },
  [397] = {
    ["col"] = 15,
    ["value"] = "=",
    ["line"] = 77,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [398] = {
    ["col"] = 17,
    ["value"] = "count",
    ["line"] = 77,
    ["type"] = "IDENTIFIER",
    ["raw"] = "count",
  },
  [399] = {
    ["col"] = 23,
    ["value"] = "+",
    ["line"] = 77,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [400] = {
    ["col"] = 25,
    ["value"] = 1,
    ["line"] = 77,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [401] = {
    ["col"] = 9,
    ["value"] = "return",
    ["line"] = 78,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [402] = {
    ["col"] = 16,
    ["value"] = "function",
    ["line"] = 78,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [403] = {
    ["col"] = 24,
    ["value"] = "(",
    ["line"] = 78,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [404] = {
    ["col"] = 25,
    ["value"] = ")",
    ["line"] = 78,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [405] = {
    ["col"] = 13,
    ["value"] = "return",
    ["line"] = 79,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [406] = {
    ["col"] = 20,
    ["value"] = "count",
    ["line"] = 79,
    ["type"] = "IDENTIFIER",
    ["raw"] = "count",
  },
  [407] = {
    ["col"] = 9,
    ["value"] = "end",
    ["line"] = 80,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [408] = {
    ["col"] = 5,
    ["value"] = "end",
    ["line"] = 81,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [409] = {
    ["col"] = 1,
    ["value"] = "end",
    ["line"] = 82,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [410] = {
    ["col"] = 4,
    ["value"] = ")",
    ["line"] = 82,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [411] = {
    ["col"] = 5,
    ["value"] = "(",
    ["line"] = 82,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [412] = {
    ["col"] = 6,
    ["value"] = 10,
    ["line"] = 82,
    ["type"] = "NUMBER",
    ["raw"] = "10",
  },
  [413] = {
    ["col"] = 8,
    ["value"] = ")",
    ["line"] = 82,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [414] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 84,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [415] = {
    ["col"] = 7,
    ["value"] = "co",
    ["line"] = 84,
    ["type"] = "IDENTIFIER",
    ["raw"] = "co",
  },
  [416] = {
    ["col"] = 10,
    ["value"] = "=",
    ["line"] = 84,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [417] = {
    ["col"] = 12,
    ["value"] = "coroutine",
    ["line"] = 84,
    ["type"] = "IDENTIFIER",
    ["raw"] = "coroutine",
  },
  [418] = {
    ["col"] = 21,
    ["value"] = ".",
    ["line"] = 84,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [419] = {
    ["col"] = 22,
    ["value"] = "create",
    ["line"] = 84,
    ["type"] = "IDENTIFIER",
    ["raw"] = "create",
  },
  [420] = {
    ["col"] = 28,
    ["value"] = "(",
    ["line"] = 84,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [421] = {
    ["col"] = 29,
    ["value"] = "function",
    ["line"] = 84,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [422] = {
    ["col"] = 37,
    ["value"] = "(",
    ["line"] = 84,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [423] = {
    ["col"] = 38,
    ["value"] = ")",
    ["line"] = 84,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [424] = {
    ["col"] = 5,
    ["value"] = "return",
    ["line"] = 85,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [425] = {
    ["col"] = 12,
    ["value"] = "(",
    ["line"] = 85,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [426] = {
    ["col"] = 13,
    ["value"] = "function",
    ["line"] = 85,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [427] = {
    ["col"] = 21,
    ["value"] = "(",
    ["line"] = 85,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [428] = {
    ["col"] = 22,
    ["value"] = ")",
    ["line"] = 85,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [429] = {
    ["col"] = 9,
    ["value"] = "return",
    ["line"] = 86,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [430] = {
    ["col"] = 16,
    ["value"] = "result from coroutine",
    ["line"] = 86,
    ["type"] = "STRING",
    ["raw"] = "\"result from coroutine\"",
  },
  [431] = {
    ["col"] = 5,
    ["value"] = "end",
    ["line"] = 87,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [432] = {
    ["col"] = 8,
    ["value"] = ")",
    ["line"] = 87,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [433] = {
    ["col"] = 9,
    ["value"] = "(",
    ["line"] = 87,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [434] = {
    ["col"] = 10,
    ["value"] = ")",
    ["line"] = 87,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [435] = {
    ["col"] = 1,
    ["value"] = "end",
    ["line"] = 88,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [436] = {
    ["col"] = 4,
    ["value"] = ")",
    ["line"] = 88,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [437] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 90,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [438] = {
    ["col"] = 7,
    ["value"] = "chained",
    ["line"] = 90,
    ["type"] = "IDENTIFIER",
    ["raw"] = "chained",
  },
  [439] = {
    ["col"] = 15,
    ["value"] = "=",
    ["line"] = 90,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [440] = {
    ["col"] = 17,
    ["value"] = 1,
    ["line"] = 90,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [441] = {
    ["col"] = 19,
    ["value"] = "<",
    ["line"] = 90,
    ["type"] = "LT",
    ["raw"] = "<",
  },
  [442] = {
    ["col"] = 21,
    ["value"] = 2,
    ["line"] = 90,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [443] = {
    ["col"] = 23,
    ["value"] = "and",
    ["line"] = 90,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [444] = {
    ["col"] = 27,
    ["value"] = 2,
    ["line"] = 90,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [445] = {
    ["col"] = 29,
    ["value"] = "<",
    ["line"] = 90,
    ["type"] = "LT",
    ["raw"] = "<",
  },
  [446] = {
    ["col"] = 31,
    ["value"] = 3,
    ["line"] = 90,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [447] = {
    ["col"] = 33,
    ["value"] = "and",
    ["line"] = 90,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [448] = {
    ["col"] = 37,
    ["value"] = 3,
    ["line"] = 90,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [449] = {
    ["col"] = 39,
    ["value"] = "<",
    ["line"] = 90,
    ["type"] = "LT",
    ["raw"] = "<",
  },
  [450] = {
    ["col"] = 41,
    ["value"] = 4,
    ["line"] = 90,
    ["type"] = "NUMBER",
    ["raw"] = "4",
  },
  [451] = {
    ["col"] = 43,
    ["value"] = "and",
    ["line"] = 90,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [452] = {
    ["col"] = 47,
    ["value"] = 4,
    ["line"] = 90,
    ["type"] = "NUMBER",
    ["raw"] = "4",
  },
  [453] = {
    ["col"] = 49,
    ["value"] = "<",
    ["line"] = 90,
    ["type"] = "LT",
    ["raw"] = "<",
  },
  [454] = {
    ["col"] = 51,
    ["value"] = 5,
    ["line"] = 90,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [455] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 92,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [456] = {
    ["col"] = 7,
    ["value"] = "logic_nest",
    ["line"] = 92,
    ["type"] = "IDENTIFIER",
    ["raw"] = "logic_nest",
  },
  [457] = {
    ["col"] = 18,
    ["value"] = "=",
    ["line"] = 92,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [458] = {
    ["col"] = 20,
    ["value"] = "(",
    ["line"] = 92,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [459] = {
    ["col"] = 21,
    ["value"] = 5,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [460] = {
    ["col"] = 23,
    ["value"] = ">",
    ["line"] = 92,
    ["type"] = "GT",
    ["raw"] = ">",
  },
  [461] = {
    ["col"] = 25,
    ["value"] = 3,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [462] = {
    ["col"] = 27,
    ["value"] = "and",
    ["line"] = 92,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [463] = {
    ["col"] = 31,
    ["value"] = "(",
    ["line"] = 92,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [464] = {
    ["col"] = 32,
    ["value"] = 4,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "4",
  },
  [465] = {
    ["col"] = 34,
    ["value"] = "<",
    ["line"] = 92,
    ["type"] = "LT",
    ["raw"] = "<",
  },
  [466] = {
    ["col"] = 36,
    ["value"] = 7,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "7",
  },
  [467] = {
    ["col"] = 38,
    ["value"] = "or",
    ["line"] = 92,
    ["type"] = "KEYWORD",
    ["raw"] = "or",
  },
  [468] = {
    ["col"] = 41,
    ["value"] = "(",
    ["line"] = 92,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [469] = {
    ["col"] = 42,
    ["value"] = 2,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [470] = {
    ["col"] = 44,
    ["value"] = ">",
    ["line"] = 92,
    ["type"] = "GT",
    ["raw"] = ">",
  },
  [471] = {
    ["col"] = 46,
    ["value"] = 1,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [472] = {
    ["col"] = 48,
    ["value"] = "and",
    ["line"] = 92,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [473] = {
    ["col"] = 52,
    ["value"] = "(",
    ["line"] = 92,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [474] = {
    ["col"] = 53,
    ["value"] = 6,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "6",
  },
  [475] = {
    ["col"] = 55,
    ["value"] = "<",
    ["line"] = 92,
    ["type"] = "LT",
    ["raw"] = "<",
  },
  [476] = {
    ["col"] = 57,
    ["value"] = 10,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "10",
  },
  [477] = {
    ["col"] = 60,
    ["value"] = "or",
    ["line"] = 92,
    ["type"] = "KEYWORD",
    ["raw"] = "or",
  },
  [478] = {
    ["col"] = 63,
    ["value"] = 3,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [479] = {
    ["col"] = 65,
    ["value"] = ">",
    ["line"] = 92,
    ["type"] = "GT",
    ["raw"] = ">",
  },
  [480] = {
    ["col"] = 67,
    ["value"] = 1,
    ["line"] = 92,
    ["type"] = "NUMBER",
    ["raw"] = "1",
  },
  [481] = {
    ["col"] = 68,
    ["value"] = ")",
    ["line"] = 92,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [482] = {
    ["col"] = 69,
    ["value"] = ")",
    ["line"] = 92,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [483] = {
    ["col"] = 70,
    ["value"] = ")",
    ["line"] = 92,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [484] = {
    ["col"] = 71,
    ["value"] = ")",
    ["line"] = 92,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [485] = {
    ["col"] = 1,
    ["value"] = "local",
    ["line"] = 94,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
  },
  [486] = {
    ["col"] = 7,
    ["value"] = "combined",
    ["line"] = 94,
    ["type"] = "IDENTIFIER",
    ["raw"] = "combined",
  },
  [487] = {
    ["col"] = 16,
    ["value"] = "=",
    ["line"] = 94,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [488] = {
    ["col"] = 18,
    ["value"] = "(",
    ["line"] = 94,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [489] = {
    ["col"] = 19,
    ["value"] = "(",
    ["line"] = 94,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [490] = {
    ["col"] = 20,
    ["value"] = 5,
    ["line"] = 94,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [491] = {
    ["col"] = 22,
    ["value"] = "+",
    ["line"] = 94,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [492] = {
    ["col"] = 24,
    ["value"] = 3,
    ["line"] = 94,
    ["type"] = "NUMBER",
    ["raw"] = "3",
  },
  [493] = {
    ["col"] = 25,
    ["value"] = ")",
    ["line"] = 94,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [494] = {
    ["col"] = 27,
    ["value"] = "*",
    ["line"] = 94,
    ["type"] = "MUL",
    ["raw"] = "*",
  },
  [495] = {
    ["col"] = 29,
    ["value"] = 2,
    ["line"] = 94,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [496] = {
    ["col"] = 31,
    ["value"] = "-",
    ["line"] = 94,
    ["type"] = "SUB",
    ["raw"] = "-",
  },
  [497] = {
    ["col"] = 33,
    ["value"] = "(",
    ["line"] = 94,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [498] = {
    ["col"] = 34,
    ["value"] = 10,
    ["line"] = 94,
    ["type"] = "NUMBER",
    ["raw"] = "10",
  },
  [499] = {
    ["col"] = 37,
    ["value"] = "/",
    ["line"] = 94,
    ["type"] = "DIV",
    ["raw"] = "/",
  },
  [500] = {
    ["col"] = 39,
    ["value"] = 2,
    ["line"] = 94,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [501] = {
    ["col"] = 40,
    ["value"] = ")",
    ["line"] = 94,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [502] = {
    ["col"] = 41,
    ["value"] = ")",
    ["line"] = 94,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [503] = {
    ["col"] = 43,
    ["value"] = "+",
    ["line"] = 94,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [504] = {
    ["col"] = 17,
    ["value"] = "(",
    ["line"] = 95,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [505] = {
    ["col"] = 18,
    ["value"] = "function",
    ["line"] = 95,
    ["type"] = "KEYWORD",
    ["raw"] = "function",
  },
  [506] = {
    ["col"] = 26,
    ["value"] = "(",
    ["line"] = 95,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [507] = {
    ["col"] = 27,
    ["value"] = "x",
    ["line"] = 95,
    ["type"] = "IDENTIFIER",
    ["raw"] = "x",
  },
  [508] = {
    ["col"] = 28,
    ["value"] = ")",
    ["line"] = 95,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [509] = {
    ["col"] = 30,
    ["value"] = "return",
    ["line"] = 95,
    ["type"] = "KEYWORD",
    ["raw"] = "return",
  },
  [510] = {
    ["col"] = 37,
    ["value"] = "x",
    ["line"] = 95,
    ["type"] = "IDENTIFIER",
    ["raw"] = "x",
  },
  [511] = {
    ["col"] = 39,
    ["value"] = "*",
    ["line"] = 95,
    ["type"] = "MUL",
    ["raw"] = "*",
  },
  [512] = {
    ["col"] = 41,
    ["value"] = 2,
    ["line"] = 95,
    ["type"] = "NUMBER",
    ["raw"] = "2",
  },
  [513] = {
    ["col"] = 43,
    ["value"] = "end",
    ["line"] = 95,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
  },
  [514] = {
    ["col"] = 46,
    ["value"] = ")",
    ["line"] = 95,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [515] = {
    ["col"] = 47,
    ["value"] = "(",
    ["line"] = 95,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [516] = {
    ["col"] = 48,
    ["value"] = 5,
    ["line"] = 95,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [517] = {
    ["col"] = 49,
    ["value"] = ")",
    ["line"] = 95,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [518] = {
    ["col"] = 51,
    ["value"] = "+",
    ["line"] = 95,
    ["type"] = "ADD",
    ["raw"] = "+",
  },
  [519] = {
    ["col"] = 17,
    ["value"] = "(",
    ["line"] = 96,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [520] = {
    ["col"] = 18,
    ["value"] = "#",
    ["line"] = 96,
    ["type"] = "LEN",
    ["raw"] = "#",
  },
  [521] = {
    ["col"] = 19,
    ["value"] = "test",
    ["line"] = 96,
    ["type"] = "STRING",
    ["raw"] = "\"test\"",
  },
  [522] = {
    ["col"] = 26,
    ["value"] = ">=",
    ["line"] = 96,
    ["type"] = "GE",
    ["raw"] = ">=",
  },
  [523] = {
    ["col"] = 29,
    ["value"] = 4,
    ["line"] = 96,
    ["type"] = "NUMBER",
    ["raw"] = "4",
  },
  [524] = {
    ["col"] = 31,
    ["value"] = "and",
    ["line"] = 96,
    ["type"] = "KEYWORD",
    ["raw"] = "and",
  },
  [525] = {
    ["col"] = 35,
    ["value"] = 10,
    ["line"] = 96,
    ["type"] = "NUMBER",
    ["raw"] = "10",
  },
  [526] = {
    ["col"] = 38,
    ["value"] = "or",
    ["line"] = 96,
    ["type"] = "KEYWORD",
    ["raw"] = "or",
  },
  [527] = {
    ["col"] = 41,
    ["value"] = 5,
    ["line"] = 96,
    ["type"] = "NUMBER",
    ["raw"] = "5",
  },
  [528] = {
    ["col"] = 42,
    ["value"] = ")",
    ["line"] = 96,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [529] = {
    ["col"] = 44,
    ["value"] = "*",
    ["line"] = 96,
    ["type"] = "MUL",
    ["raw"] = "*",
  },
  [530] = {
    ["col"] = 17,
    ["value"] = "(",
    ["line"] = 97,
    ["type"] = "LPAREN",
    ["raw"] = "(",
  },
  [531] = {
    ["col"] = 18,
    ["value"] = "{",
    ["line"] = 97,
    ["type"] = "LBRACE",
    ["raw"] = "{",
  },
  [532] = {
    ["col"] = 19,
    ["value"] = "value",
    ["line"] = 97,
    ["type"] = "IDENTIFIER",
    ["raw"] = "value",
  },
  [533] = {
    ["col"] = 25,
    ["value"] = "=",
    ["line"] = 97,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
  },
  [534] = {
    ["col"] = 27,
    ["value"] = 10,
    ["line"] = 97,
    ["type"] = "NUMBER",
    ["raw"] = "10",
  },
  [535] = {
    ["col"] = 29,
    ["value"] = "}",
    ["line"] = 97,
    ["type"] = "RBRACE",
    ["raw"] = "}",
  },
  [536] = {
    ["col"] = 30,
    ["value"] = ")",
    ["line"] = 97,
    ["type"] = "RPAREN",
    ["raw"] = ")",
  },
  [537] = {
    ["col"] = 31,
    ["value"] = ".",
    ["line"] = 97,
    ["type"] = "DOT",
    ["raw"] = ".",
  },
  [538] = {
    ["col"] = 32,
    ["value"] = "value",
    ["line"] = 97,
    ["type"] = "IDENTIFIER",
    ["raw"] = "value",
  },
  [539] = {
    ["col"] = 38,
    ["value"] = "",
    ["line"] = 97,
    ["type"] = "EOF",
    ["raw"] = "",
  },
}