-- lua cli.lua parse simple_script.lua --format=lua --output=both

return {
  ast = {
  ["body"] = {
    [1] = {
      ["init"] = {
        [1] = {
          ["raw"] = "\"User\"",
          ["type"] = "StringLiteral",
          ["value"] = "User",
        },
      },
      ["type"] = "LocalStatement",
      ["variables"] = {
        [1] = {
          ["type"] = "Identifier",
          ["name"] = "name",
        },
      },
    },
    [2] = {
      ["init"] = {
        [1] = {
          ["raw"] = "25",
          ["type"] = "NumericLiteral",
          ["value"] = 25,
        },
      },
      ["type"] = "LocalStatement",
      ["variables"] = {
        [1] = {
          ["type"] = "Identifier",
          ["name"] = "age",
        },
      },
    },
    [3] = {
      ["init"] = {
        [1] = {
          ["raw"] = "19.99",
          ["type"] = "NumericLiteral",
          ["value"] = 19.99,
        },
      },
      ["type"] = "LocalStatement",
      ["variables"] = {
        [1] = {
          ["type"] = "Identifier",
          ["name"] = "price",
        },
      },
    },
    [4] = {
      ["init"] = {
        [1] = {
          ["type"] = "BooleanLiteral",
          ["value"] = true,
        },
      },
      ["type"] = "LocalStatement",
      ["variables"] = {
        [1] = {
          ["type"] = "Identifier",
          ["name"] = "is_active",
        },
      },
    },
    [5] = {
      ["type"] = "CallStatement",
      ["expression"] = {
        ["potential_metamethod"] = "__call",
        ["base"] = {
          ["type"] = "Identifier",
          ["name"] = "print",
        },
        ["type"] = "CallExpression",
        ["arguments"] = {
          [1] = {
            ["raw"] = "\"Hello, welcome to Lua!\"",
            ["type"] = "StringLiteral",
            ["value"] = "Hello, welcome to Lua!",
          },
        },
        ["is_method_call"] = false,
        ["has_metamethod"] = true,
      },
    },
    [6] = {
      ["type"] = "CallStatement",
      ["expression"] = {
        ["potential_metamethod"] = "__call",
        ["base"] = {
          ["type"] = "Identifier",
          ["name"] = "print",
        },
        ["type"] = "CallExpression",
        ["arguments"] = {
          [1] = {
            ["substituted_operator"] = "..",
            ["original_right"] = {
              ["type"] = "Identifier",
              ["name"] = "name",
            },
            ["operator"] = "..",
            ["original_left"] = {
              ["raw"] = "\"Name: \"",
              ["type"] = "StringLiteral",
              ["value"] = "Name: ",
            },
            ["potential_metamethod"] = "__concat",
            ["negate_result"] = false,
            ["type"] = "BinaryExpression",
            ["left"] = {
              ["raw"] = "\"Name: \"",
              ["type"] = "StringLiteral",
              ["value"] = "Name: ",
            },
            ["swap_operands"] = false,
            ["has_metamethod"] = true,
            ["right"] = {
              ["type"] = "Identifier",
              ["name"] = "name",
            },
          },
        },
        ["is_method_call"] = false,
        ["has_metamethod"] = true,
      },
    },
    [7] = {
      ["type"] = "CallStatement",
      ["expression"] = {
        ["potential_metamethod"] = "__call",
        ["base"] = {
          ["type"] = "Identifier",
          ["name"] = "print",
        },
        ["type"] = "CallExpression",
        ["arguments"] = {
          [1] = {
            ["substituted_operator"] = "..",
            ["original_right"] = {
              ["type"] = "Identifier",
              ["name"] = "age",
            },
            ["operator"] = "..",
            ["original_left"] = {
              ["raw"] = "\"Age: \"",
              ["type"] = "StringLiteral",
              ["value"] = "Age: ",
            },
            ["potential_metamethod"] = "__concat",
            ["negate_result"] = false,
            ["type"] = "BinaryExpression",
            ["left"] = {
              ["raw"] = "\"Age: \"",
              ["type"] = "StringLiteral",
              ["value"] = "Age: ",
            },
            ["swap_operands"] = false,
            ["has_metamethod"] = true,
            ["right"] = {
              ["type"] = "Identifier",
              ["name"] = "age",
            },
          },
        },
        ["is_method_call"] = false,
        ["has_metamethod"] = true,
      },
    },
    [8] = {
      ["type"] = "CallStatement",
      ["expression"] = {
        ["potential_metamethod"] = "__call",
        ["base"] = {
          ["type"] = "Identifier",
          ["name"] = "print",
        },
        ["type"] = "CallExpression",
        ["arguments"] = {
          [1] = {
            ["substituted_operator"] = "..",
            ["original_right"] = {
              ["type"] = "Identifier",
              ["name"] = "price",
            },
            ["operator"] = "..",
            ["original_left"] = {
              ["raw"] = "\"Price: $\"",
              ["type"] = "StringLiteral",
              ["value"] = "Price: $",
            },
            ["potential_metamethod"] = "__concat",
            ["negate_result"] = false,
            ["type"] = "BinaryExpression",
            ["left"] = {
              ["raw"] = "\"Price: $\"",
              ["type"] = "StringLiteral",
              ["value"] = "Price: $",
            },
            ["swap_operands"] = false,
            ["has_metamethod"] = true,
            ["right"] = {
              ["type"] = "Identifier",
              ["name"] = "price",
            },
          },
        },
        ["is_method_call"] = false,
        ["has_metamethod"] = true,
      },
    },
    [9] = {
      ["type"] = "IfStatement",
      ["clauses"] = {
        [1] = {
          ["condition"] = {
            ["type"] = "Identifier",
            ["name"] = "is_active",
          },
          ["type"] = "IfClause",
          ["body"] = {
            [1] = {
              ["type"] = "CallStatement",
              ["expression"] = {
                ["potential_metamethod"] = "__call",
                ["base"] = {
                  ["type"] = "Identifier",
                  ["name"] = "print",
                },
                ["type"] = "CallExpression",
                ["arguments"] = {
                  [1] = {
                    ["raw"] = "\"Status: Active\"",
                    ["type"] = "StringLiteral",
                    ["value"] = "Status: Active",
                  },
                },
                ["is_method_call"] = false,
                ["has_metamethod"] = true,
              },
            },
          },
        },
        [2] = {
          ["type"] = "ElseClause",
          ["body"] = {
            [1] = {
              ["type"] = "CallStatement",
              ["expression"] = {
                ["potential_metamethod"] = "__call",
                ["base"] = {
                  ["type"] = "Identifier",
                  ["name"] = "print",
                },
                ["type"] = "CallExpression",
                ["arguments"] = {
                  [1] = {
                    ["raw"] = "\"Status: Inactive\"",
                    ["type"] = "StringLiteral",
                    ["value"] = "Status: Inactive",
                  },
                },
                ["is_method_call"] = false,
                ["has_metamethod"] = true,
              },
            },
          },
        },
      },
    },
    [10] = {
      ["init"] = {
        [1] = {
          ["raw"] = "0.08",
          ["type"] = "NumericLiteral",
          ["value"] = 0.08,
        },
      },
      ["type"] = "LocalStatement",
      ["variables"] = {
        [1] = {
          ["type"] = "Identifier",
          ["name"] = "tax_rate",
        },
      },
    },
    [11] = {
      ["init"] = {
        [1] = {
          ["substituted_operator"] = "+",
          ["original_right"] = {
            ["substituted_operator"] = "*",
            ["original_right"] = {
              ["type"] = "Identifier",
              ["name"] = "tax_rate",
            },
            ["operator"] = "*",
            ["original_left"] = {
              ["type"] = "Identifier",
              ["name"] = "price",
            },
            ["potential_metamethod"] = "__mul",
            ["negate_result"] = false,
            ["type"] = "BinaryExpression",
            ["left"] = {
              ["type"] = "Identifier",
              ["name"] = "price",
            },
            ["swap_operands"] = false,
            ["has_metamethod"] = true,
            ["right"] = {
              ["type"] = "Identifier",
              ["name"] = "tax_rate",
            },
          },
          ["operator"] = "+",
          ["original_left"] = {
            ["type"] = "Identifier",
            ["name"] = "price",
          },
          ["potential_metamethod"] = "__add",
          ["negate_result"] = false,
          ["type"] = "BinaryExpression",
          ["left"] = {
            ["type"] = "Identifier",
            ["name"] = "price",
          },
          ["swap_operands"] = false,
          ["has_metamethod"] = true,
          ["right"] = {
            ["substituted_operator"] = "*",
            ["original_right"] = {
              ["type"] = "Identifier",
              ["name"] = "tax_rate",
            },
            ["operator"] = "*",
            ["original_left"] = {
              ["type"] = "Identifier",
              ["name"] = "price",
            },
            ["potential_metamethod"] = "__mul",
            ["negate_result"] = false,
            ["type"] = "BinaryExpression",
            ["left"] = {
              ["type"] = "Identifier",
              ["name"] = "price",
            },
            ["swap_operands"] = false,
            ["has_metamethod"] = true,
            ["right"] = {
              ["type"] = "Identifier",
              ["name"] = "tax_rate",
            },
          },
        },
      },
      ["type"] = "LocalStatement",
      ["variables"] = {
        [1] = {
          ["type"] = "Identifier",
          ["name"] = "total_price",
        },
      },
    },
    [12] = {
      ["type"] = "CallStatement",
      ["expression"] = {
        ["potential_metamethod"] = "__call",
        ["base"] = {
          ["type"] = "Identifier",
          ["name"] = "print",
        },
        ["type"] = "CallExpression",
        ["arguments"] = {
          [1] = {
            ["substituted_operator"] = "..",
            ["original_right"] = {
              ["type"] = "Identifier",
              ["name"] = "total_price",
            },
            ["operator"] = "..",
            ["original_left"] = {
              ["raw"] = "\"Total price with tax: $\"",
              ["type"] = "StringLiteral",
              ["value"] = "Total price with tax: $",
            },
            ["potential_metamethod"] = "__concat",
            ["negate_result"] = false,
            ["type"] = "BinaryExpression",
            ["left"] = {
              ["raw"] = "\"Total price with tax: $\"",
              ["type"] = "StringLiteral",
              ["value"] = "Total price with tax: $",
            },
            ["swap_operands"] = false,
            ["has_metamethod"] = true,
            ["right"] = {
              ["type"] = "Identifier",
              ["name"] = "total_price",
            },
          },
        },
        ["is_method_call"] = false,
        ["has_metamethod"] = true,
      },
    },
    [13] = {
      ["init"] = {
        [1] = {
          ["substituted_operator"] = "..",
          ["original_right"] = {
            ["substituted_operator"] = "..",
            ["original_right"] = {
              ["raw"] = "\"day!\"",
              ["type"] = "StringLiteral",
              ["value"] = "day!",
            },
            ["operator"] = "..",
            ["original_left"] = {
              ["raw"] = "\"nice \"",
              ["type"] = "StringLiteral",
              ["value"] = "nice ",
            },
            ["potential_metamethod"] = "__concat",
            ["negate_result"] = false,
            ["type"] = "BinaryExpression",
            ["left"] = {
              ["raw"] = "\"nice \"",
              ["type"] = "StringLiteral",
              ["value"] = "nice ",
            },
            ["swap_operands"] = false,
            ["has_metamethod"] = true,
            ["right"] = {
              ["raw"] = "\"day!\"",
              ["type"] = "StringLiteral",
              ["value"] = "day!",
            },
          },
          ["operator"] = "..",
          ["original_left"] = {
            ["raw"] = "\"Have a \"",
            ["type"] = "StringLiteral",
            ["value"] = "Have a ",
          },
          ["potential_metamethod"] = "__concat",
          ["negate_result"] = false,
          ["type"] = "BinaryExpression",
          ["left"] = {
            ["raw"] = "\"Have a \"",
            ["type"] = "StringLiteral",
            ["value"] = "Have a ",
          },
          ["swap_operands"] = false,
          ["has_metamethod"] = true,
          ["right"] = {
            ["substituted_operator"] = "..",
            ["original_right"] = {
              ["raw"] = "\"day!\"",
              ["type"] = "StringLiteral",
              ["value"] = "day!",
            },
            ["operator"] = "..",
            ["original_left"] = {
              ["raw"] = "\"nice \"",
              ["type"] = "StringLiteral",
              ["value"] = "nice ",
            },
            ["potential_metamethod"] = "__concat",
            ["negate_result"] = false,
            ["type"] = "BinaryExpression",
            ["left"] = {
              ["raw"] = "\"nice \"",
              ["type"] = "StringLiteral",
              ["value"] = "nice ",
            },
            ["swap_operands"] = false,
            ["has_metamethod"] = true,
            ["right"] = {
              ["raw"] = "\"day!\"",
              ["type"] = "StringLiteral",
              ["value"] = "day!",
            },
          },
        },
      },
      ["type"] = "LocalStatement",
      ["variables"] = {
        [1] = {
          ["type"] = "Identifier",
          ["name"] = "greeting",
        },
      },
    },
    [14] = {
      ["type"] = "CallStatement",
      ["expression"] = {
        ["potential_metamethod"] = "__call",
        ["base"] = {
          ["type"] = "Identifier",
          ["name"] = "print",
        },
        ["type"] = "CallExpression",
        ["arguments"] = {
          [1] = {
            ["type"] = "Identifier",
            ["name"] = "greeting",
          },
        },
        ["is_method_call"] = false,
        ["has_metamethod"] = true,
      },
    },
  },
  ["type"] = "Chunk",
  ["comments"] = {
  },
},
  tokens = {
  [1] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
    ["line"] = 1,
    ["value"] = "local",
  },
  [2] = {
    ["col"] = 7,
    ["type"] = "IDENTIFIER",
    ["raw"] = "name",
    ["line"] = 1,
    ["value"] = "name",
  },
  [3] = {
    ["col"] = 12,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
    ["line"] = 1,
    ["value"] = "=",
  },
  [4] = {
    ["col"] = 14,
    ["type"] = "STRING",
    ["raw"] = "\"User\"",
    ["line"] = 1,
    ["value"] = "User",
  },
  [5] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
    ["line"] = 2,
    ["value"] = "local",
  },
  [6] = {
    ["col"] = 7,
    ["type"] = "IDENTIFIER",
    ["raw"] = "age",
    ["line"] = 2,
    ["value"] = "age",
  },
  [7] = {
    ["col"] = 11,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
    ["line"] = 2,
    ["value"] = "=",
  },
  [8] = {
    ["col"] = 13,
    ["type"] = "NUMBER",
    ["raw"] = "25",
    ["line"] = 2,
    ["value"] = 25,
  },
  [9] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
    ["line"] = 3,
    ["value"] = "local",
  },
  [10] = {
    ["col"] = 7,
    ["type"] = "IDENTIFIER",
    ["raw"] = "price",
    ["line"] = 3,
    ["value"] = "price",
  },
  [11] = {
    ["col"] = 13,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
    ["line"] = 3,
    ["value"] = "=",
  },
  [12] = {
    ["col"] = 15,
    ["type"] = "NUMBER",
    ["raw"] = "19.99",
    ["line"] = 3,
    ["value"] = 19.99,
  },
  [13] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
    ["line"] = 4,
    ["value"] = "local",
  },
  [14] = {
    ["col"] = 7,
    ["type"] = "IDENTIFIER",
    ["raw"] = "is_active",
    ["line"] = 4,
    ["value"] = "is_active",
  },
  [15] = {
    ["col"] = 17,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
    ["line"] = 4,
    ["value"] = "=",
  },
  [16] = {
    ["col"] = 19,
    ["type"] = "TRUE",
    ["raw"] = "true",
    ["line"] = 4,
    ["value"] = true,
  },
  [17] = {
    ["col"] = 1,
    ["type"] = "IDENTIFIER",
    ["raw"] = "print",
    ["line"] = 6,
    ["value"] = "print",
  },
  [18] = {
    ["col"] = 6,
    ["type"] = "LPAREN",
    ["raw"] = "(",
    ["line"] = 6,
    ["value"] = "(",
  },
  [19] = {
    ["col"] = 7,
    ["type"] = "STRING",
    ["raw"] = "\"Hello, welcome to Lua!\"",
    ["line"] = 6,
    ["value"] = "Hello, welcome to Lua!",
  },
  [20] = {
    ["col"] = 31,
    ["type"] = "RPAREN",
    ["raw"] = ")",
    ["line"] = 6,
    ["value"] = ")",
  },
  [21] = {
    ["col"] = 1,
    ["type"] = "IDENTIFIER",
    ["raw"] = "print",
    ["line"] = 7,
    ["value"] = "print",
  },
  [22] = {
    ["col"] = 6,
    ["type"] = "LPAREN",
    ["raw"] = "(",
    ["line"] = 7,
    ["value"] = "(",
  },
  [23] = {
    ["col"] = 7,
    ["type"] = "STRING",
    ["raw"] = "\"Name: \"",
    ["line"] = 7,
    ["value"] = "Name: ",
  },
  [24] = {
    ["col"] = 16,
    ["type"] = "CONCAT",
    ["raw"] = "..",
    ["line"] = 7,
    ["value"] = "..",
  },
  [25] = {
    ["col"] = 19,
    ["type"] = "IDENTIFIER",
    ["raw"] = "name",
    ["line"] = 7,
    ["value"] = "name",
  },
  [26] = {
    ["col"] = 23,
    ["type"] = "RPAREN",
    ["raw"] = ")",
    ["line"] = 7,
    ["value"] = ")",
  },
  [27] = {
    ["col"] = 1,
    ["type"] = "IDENTIFIER",
    ["raw"] = "print",
    ["line"] = 8,
    ["value"] = "print",
  },
  [28] = {
    ["col"] = 6,
    ["type"] = "LPAREN",
    ["raw"] = "(",
    ["line"] = 8,
    ["value"] = "(",
  },
  [29] = {
    ["col"] = 7,
    ["type"] = "STRING",
    ["raw"] = "\"Age: \"",
    ["line"] = 8,
    ["value"] = "Age: ",
  },
  [30] = {
    ["col"] = 15,
    ["type"] = "CONCAT",
    ["raw"] = "..",
    ["line"] = 8,
    ["value"] = "..",
  },
  [31] = {
    ["col"] = 18,
    ["type"] = "IDENTIFIER",
    ["raw"] = "age",
    ["line"] = 8,
    ["value"] = "age",
  },
  [32] = {
    ["col"] = 21,
    ["type"] = "RPAREN",
    ["raw"] = ")",
    ["line"] = 8,
    ["value"] = ")",
  },
  [33] = {
    ["col"] = 1,
    ["type"] = "IDENTIFIER",
    ["raw"] = "print",
    ["line"] = 9,
    ["value"] = "print",
  },
  [34] = {
    ["col"] = 6,
    ["type"] = "LPAREN",
    ["raw"] = "(",
    ["line"] = 9,
    ["value"] = "(",
  },
  [35] = {
    ["col"] = 7,
    ["type"] = "STRING",
    ["raw"] = "\"Price: $\"",
    ["line"] = 9,
    ["value"] = "Price: $",
  },
  [36] = {
    ["col"] = 18,
    ["type"] = "CONCAT",
    ["raw"] = "..",
    ["line"] = 9,
    ["value"] = "..",
  },
  [37] = {
    ["col"] = 21,
    ["type"] = "IDENTIFIER",
    ["raw"] = "price",
    ["line"] = 9,
    ["value"] = "price",
  },
  [38] = {
    ["col"] = 26,
    ["type"] = "RPAREN",
    ["raw"] = ")",
    ["line"] = 9,
    ["value"] = ")",
  },
  [39] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "if",
    ["line"] = 11,
    ["value"] = "if",
  },
  [40] = {
    ["col"] = 4,
    ["type"] = "IDENTIFIER",
    ["raw"] = "is_active",
    ["line"] = 11,
    ["value"] = "is_active",
  },
  [41] = {
    ["col"] = 14,
    ["type"] = "KEYWORD",
    ["raw"] = "then",
    ["line"] = 11,
    ["value"] = "then",
  },
  [42] = {
    ["col"] = 5,
    ["type"] = "IDENTIFIER",
    ["raw"] = "print",
    ["line"] = 12,
    ["value"] = "print",
  },
  [43] = {
    ["col"] = 10,
    ["type"] = "LPAREN",
    ["raw"] = "(",
    ["line"] = 12,
    ["value"] = "(",
  },
  [44] = {
    ["col"] = 11,
    ["type"] = "STRING",
    ["raw"] = "\"Status: Active\"",
    ["line"] = 12,
    ["value"] = "Status: Active",
  },
  [45] = {
    ["col"] = 27,
    ["type"] = "RPAREN",
    ["raw"] = ")",
    ["line"] = 12,
    ["value"] = ")",
  },
  [46] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "else",
    ["line"] = 13,
    ["value"] = "else",
  },
  [47] = {
    ["col"] = 5,
    ["type"] = "IDENTIFIER",
    ["raw"] = "print",
    ["line"] = 14,
    ["value"] = "print",
  },
  [48] = {
    ["col"] = 10,
    ["type"] = "LPAREN",
    ["raw"] = "(",
    ["line"] = 14,
    ["value"] = "(",
  },
  [49] = {
    ["col"] = 11,
    ["type"] = "STRING",
    ["raw"] = "\"Status: Inactive\"",
    ["line"] = 14,
    ["value"] = "Status: Inactive",
  },
  [50] = {
    ["col"] = 29,
    ["type"] = "RPAREN",
    ["raw"] = ")",
    ["line"] = 14,
    ["value"] = ")",
  },
  [51] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "end",
    ["line"] = 15,
    ["value"] = "end",
  },
  [52] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
    ["line"] = 17,
    ["value"] = "local",
  },
  [53] = {
    ["col"] = 7,
    ["type"] = "IDENTIFIER",
    ["raw"] = "tax_rate",
    ["line"] = 17,
    ["value"] = "tax_rate",
  },
  [54] = {
    ["col"] = 16,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
    ["line"] = 17,
    ["value"] = "=",
  },
  [55] = {
    ["col"] = 18,
    ["type"] = "NUMBER",
    ["raw"] = "0.08",
    ["line"] = 17,
    ["value"] = 0.08,
  },
  [56] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
    ["line"] = 18,
    ["value"] = "local",
  },
  [57] = {
    ["col"] = 7,
    ["type"] = "IDENTIFIER",
    ["raw"] = "total_price",
    ["line"] = 18,
    ["value"] = "total_price",
  },
  [58] = {
    ["col"] = 19,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
    ["line"] = 18,
    ["value"] = "=",
  },
  [59] = {
    ["col"] = 21,
    ["type"] = "IDENTIFIER",
    ["raw"] = "price",
    ["line"] = 18,
    ["value"] = "price",
  },
  [60] = {
    ["col"] = 27,
    ["type"] = "ADD",
    ["raw"] = "+",
    ["line"] = 18,
    ["value"] = "+",
  },
  [61] = {
    ["col"] = 29,
    ["type"] = "LPAREN",
    ["raw"] = "(",
    ["line"] = 18,
    ["value"] = "(",
  },
  [62] = {
    ["col"] = 30,
    ["type"] = "IDENTIFIER",
    ["raw"] = "price",
    ["line"] = 18,
    ["value"] = "price",
  },
  [63] = {
    ["col"] = 36,
    ["type"] = "MUL",
    ["raw"] = "*",
    ["line"] = 18,
    ["value"] = "*",
  },
  [64] = {
    ["col"] = 38,
    ["type"] = "IDENTIFIER",
    ["raw"] = "tax_rate",
    ["line"] = 18,
    ["value"] = "tax_rate",
  },
  [65] = {
    ["col"] = 46,
    ["type"] = "RPAREN",
    ["raw"] = ")",
    ["line"] = 18,
    ["value"] = ")",
  },
  [66] = {
    ["col"] = 1,
    ["type"] = "IDENTIFIER",
    ["raw"] = "print",
    ["line"] = 19,
    ["value"] = "print",
  },
  [67] = {
    ["col"] = 6,
    ["type"] = "LPAREN",
    ["raw"] = "(",
    ["line"] = 19,
    ["value"] = "(",
  },
  [68] = {
    ["col"] = 7,
    ["type"] = "STRING",
    ["raw"] = "\"Total price with tax: $\"",
    ["line"] = 19,
    ["value"] = "Total price with tax: $",
  },
  [69] = {
    ["col"] = 33,
    ["type"] = "CONCAT",
    ["raw"] = "..",
    ["line"] = 19,
    ["value"] = "..",
  },
  [70] = {
    ["col"] = 36,
    ["type"] = "IDENTIFIER",
    ["raw"] = "total_price",
    ["line"] = 19,
    ["value"] = "total_price",
  },
  [71] = {
    ["col"] = 47,
    ["type"] = "RPAREN",
    ["raw"] = ")",
    ["line"] = 19,
    ["value"] = ")",
  },
  [72] = {
    ["col"] = 1,
    ["type"] = "KEYWORD",
    ["raw"] = "local",
    ["line"] = 21,
    ["value"] = "local",
  },
  [73] = {
    ["col"] = 7,
    ["type"] = "IDENTIFIER",
    ["raw"] = "greeting",
    ["line"] = 21,
    ["value"] = "greeting",
  },
  [74] = {
    ["col"] = 16,
    ["type"] = "ASSIGN",
    ["raw"] = "=",
    ["line"] = 21,
    ["value"] = "=",
  },
  [75] = {
    ["col"] = 18,
    ["type"] = "STRING",
    ["raw"] = "\"Have a \"",
    ["line"] = 21,
    ["value"] = "Have a ",
  },
  [76] = {
    ["col"] = 28,
    ["type"] = "CONCAT",
    ["raw"] = "..",
    ["line"] = 21,
    ["value"] = "..",
  },
  [77] = {
    ["col"] = 31,
    ["type"] = "STRING",
    ["raw"] = "\"nice \"",
    ["line"] = 21,
    ["value"] = "nice ",
  },
  [78] = {
    ["col"] = 39,
    ["type"] = "CONCAT",
    ["raw"] = "..",
    ["line"] = 21,
    ["value"] = "..",
  },
  [79] = {
    ["col"] = 42,
    ["type"] = "STRING",
    ["raw"] = "\"day!\"",
    ["line"] = 21,
    ["value"] = "day!",
  },
  [80] = {
    ["col"] = 1,
    ["type"] = "IDENTIFIER",
    ["raw"] = "print",
    ["line"] = 22,
    ["value"] = "print",
  },
  [81] = {
    ["col"] = 6,
    ["type"] = "LPAREN",
    ["raw"] = "(",
    ["line"] = 22,
    ["value"] = "(",
  },
  [82] = {
    ["col"] = 7,
    ["type"] = "IDENTIFIER",
    ["raw"] = "greeting",
    ["line"] = 22,
    ["value"] = "greeting",
  },
  [83] = {
    ["col"] = 15,
    ["type"] = "RPAREN",
    ["raw"] = ")",
    ["line"] = 22,
    ["value"] = ")",
  },
  [84] = {
    ["col"] = 1,
    ["type"] = "EOF",
    ["raw"] = "",
    ["line"] = 23,
    ["value"] = "",
  },
}
}